//! C FFI wrapper generation from SPEL IDL.
//!
//! Generates `extern "C"` functions that accept JSON strings and return JSON strings.
//! The generated FFI includes full transaction building via `wallet::WalletCore`.
//!
//! If the IDL has `instruction_type` set (e.g. `"multisig_core::Instruction"`),
//! the generated code imports and uses that type directly — ensuring correct
//! serde/borsh representation when the instruction is sent to the zkVM guest.
//!
//! If `instruction_type` is absent, a local enum is generated with
//! `#[derive(Serialize, Deserialize)]` which works for simple programs.

use spel_framework_core::idl::*;
use std::fmt::Write;
use crate::util::*;

/// Generate C FFI wrapper source code from an IDL.
///
/// `idl_json` is the raw JSON that was parsed into `idl`; it is embedded as a
/// static string in the generated code so `{prefix}_decode_account` can call
/// `spel_framework_core::decode::decode_account_data_try_all` at runtime.
pub fn generate_ffi(idl: &SpelIdl, idl_json: &str) -> Result<String, String> {
    let mut out = String::new();
    let prefix = snake_case(&idl.name);
    let local_enum = pascal_case(&idl.name) + "Instruction";

    // When instruction_type is set, we import it as `ProgramInstruction`.
    // When absent, we generate a local enum named `{Program}Instruction`.
    let instr_type = if idl.instruction_type.is_some() {
        "ProgramInstruction".to_string()
    } else {
        local_enum.clone()
    };

    // Header — use regular comments (//), not inner doc comments (//!), so the
    // generated file can be safely include!()'d inside a module or lib.rs.
    writeln!(out, "// Auto-generated C FFI for the {} program.", idl.name).unwrap();
    writeln!(out, "// Generated by spel-client-gen. DO NOT EDIT.").unwrap();
    writeln!(out, "//").unwrap();
    writeln!(out, "// Required JSON fields for every instruction call:").unwrap();
    writeln!(out, "//   - `wallet_path`: path to NSSA wallet directory").unwrap();
    writeln!(out, "//   - `sequencer_url`: e.g. \"http://127.0.0.1:3040\"").unwrap();
    writeln!(out, "//   - `program_id_hex`: 64-char hex string identifying the program").unwrap();
    writeln!(out).unwrap();

    // Imports
    writeln!(out, "use std::ffi::{{CStr, CString}};").unwrap();
    writeln!(out, "use std::os::raw::c_char;").unwrap();
    writeln!(out, "use serde_json::{{Value, json}};").unwrap();
    writeln!(out, "use sha2::{{Sha256, Digest}};").unwrap();
    writeln!(out, "use nssa::{{AccountId, ProgramId, PublicTransaction}};").unwrap();
    writeln!(out, "use nssa::public_transaction::{{Message, WitnessSet}};").unwrap();
    writeln!(out, "use nssa::program::Program;").unwrap();
    writeln!(out, "use nssa_core::program::PdaSeed;").unwrap();
    writeln!(out, "use sequencer_service_rpc::RpcClient as _;").unwrap();
    writeln!(out, "use wallet::WalletCore;").unwrap();

    // Embed IDL JSON for runtime decode (spel_framework_core::decode::decode_account_data_try_all).
    // Use a normal string literal with escaping instead of a raw literal to avoid the r#"..."#
    // delimiter collision if the JSON ever contains a matching sequence.
    writeln!(out).unwrap();
    let escaped = idl_json.replace('\\', "\\\\").replace('"', "\\\"");
    writeln!(out, "static PROGRAM_IDL_JSON: &str = \"{}\";", escaped).unwrap();

    // Import or generate instruction type
    if let Some(ref itype) = idl.instruction_type {
        writeln!(out, "use {} as ProgramInstruction;", itype).unwrap();
    } else {
        // Generate local instruction enum
        writeln!(out, "use serde::{{Serialize, Deserialize}};").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "#[derive(Debug, Clone, Serialize, Deserialize)]").unwrap();
        writeln!(out, "pub enum {local_enum} {{").unwrap();
        for ix in &idl.instructions {
            let variant = pascal_case(&ix.name);
            if ix.args.is_empty() {
                writeln!(out, "    {variant},").unwrap();
            } else {
                writeln!(out, "    {variant} {{").unwrap();
                for arg in &ix.args {
                    let name = rust_ident(&arg.name);
                    let ty = idl_type_to_rust(&arg.type_);
                    writeln!(out, "        {name}: {ty},").unwrap();
                }
                writeln!(out, "    }},").unwrap();
            }
        }
        writeln!(out, "}}").unwrap();
    }
    writeln!(out).unwrap();

    // Helper fns
    writeln!(out, "fn cstr_to_str<'a>(ptr: *const c_char) -> Result<&'a str, String> {{").unwrap();
    writeln!(out, "    if ptr.is_null() {{ return Err(\"null pointer\".into()); }}").unwrap();
    writeln!(out, "    unsafe {{ CStr::from_ptr(ptr) }}.to_str().map_err(|e| format!(\"invalid UTF-8: {{}}\", e))").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "fn to_cstring(s: String) -> *mut c_char {{").unwrap();
    writeln!(out, "    CString::new(s).unwrap_or_else(|_|").unwrap();
    writeln!(out, "        CString::new(r#\"{{\"success\":false,\"error\":\"null byte\"}}\"#).unwrap()").unwrap();
    writeln!(out, "    ).into_raw()").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "fn error_json(msg: &str) -> *mut c_char {{").unwrap();
    writeln!(out, "    let v = serde_json::json!(msg).to_string();").unwrap();
    writeln!(out, "    let body = format!(\"{{{{\\\"success\\\":false,\\\"error\\\":{{}}}}}}\", v);").unwrap();
    writeln!(out, "    to_cstring(body)").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Panic-safe FFI wrapper — catches panics and returns error JSON instead of aborting.
    // AssertUnwindSafe is sound here: we consume the closure and never resume after a panic.
    writeln!(out, "fn ffi_call(f: impl FnOnce() -> Result<String, String>) -> *mut c_char {{").unwrap();
    writeln!(out, "    match std::panic::catch_unwind(std::panic::AssertUnwindSafe(f)) {{").unwrap();
    writeln!(out, "        Ok(Ok(r))  => to_cstring(r),").unwrap();
    writeln!(out, "        Ok(Err(e)) => error_json(&e),").unwrap();
    writeln!(out, "        Err(payload) => {{").unwrap();
    writeln!(out, "            let msg = payload.downcast_ref::<&str>().copied()").unwrap();
    writeln!(out, "                .or_else(|| payload.downcast_ref::<String>().map(|s| s.as_str()))").unwrap();
    writeln!(out, "                .unwrap_or(\"<unknown panic>\");").unwrap();
    writeln!(out, "            error_json(&format!(\"panic: {{}}\", msg))").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // PDA helper — kept for potential use; all current call sites use compute_pda_with_program.
    writeln!(out, "#[allow(dead_code)]").unwrap();
    writeln!(out, "fn compute_pda(seeds: &[&[u8]]) -> AccountId {{").unwrap();
    writeln!(out, "    let mut hasher = Sha256::new();").unwrap();
    writeln!(out, "    for seed in seeds {{").unwrap();
    writeln!(out, "        let mut padded = [0u8; 32];").unwrap();
    writeln!(out, "        let len = seed.len().min(32);").unwrap();
    writeln!(out, "        padded[..len].copy_from_slice(&seed[..len]);").unwrap();
    writeln!(out, "        hasher.update(&padded);").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    let hash: [u8; 32] = hasher.finalize().into();").unwrap();
    writeln!(out, "    AccountId::new(hash)").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    // compute_pda_with_program: canonical PDA derivation used by fetch functions.
    // Matches spel_framework_core::pda::compute_pda exactly:
    //   single seed  → use padded 32-byte seed directly (no SHA-256)
    //   multi-seed   → SHA-256 of each padded 32-byte seed
    // Then derives AccountId from (program_id, PdaSeed) so PDAs are program-specific.
    writeln!(out, "#[allow(dead_code)]").unwrap();
    writeln!(out, "fn pda_seed_bytes(seeds: &[&[u8]]) -> Result<[u8; 32], String> {{").unwrap();
    writeln!(out, "    if seeds.is_empty() {{").unwrap();
    writeln!(out, "        return Err(\"PDA requires at least one seed\".into());").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    if seeds.len() == 1 {{").unwrap();
    writeln!(out, "        let len = seeds[0].len();").unwrap();
    writeln!(out, "        if len > 32 {{ return Err(format!(\"PDA seed exceeds 32 bytes ({{len}})\")); }}").unwrap();
    writeln!(out, "        let mut padded = [0u8; 32];").unwrap();
    writeln!(out, "        padded[..len].copy_from_slice(&seeds[0][..len]);").unwrap();
    writeln!(out, "        Ok(padded)").unwrap();
    writeln!(out, "    }} else {{").unwrap();
    writeln!(out, "        let mut hasher = Sha256::new();").unwrap();
    writeln!(out, "        for seed in seeds {{").unwrap();
    writeln!(out, "            let len = seed.len();").unwrap();
    writeln!(out, "            if len > 32 {{ return Err(format!(\"PDA seed exceeds 32 bytes ({{len}})\")); }}").unwrap();
    writeln!(out, "            let mut padded = [0u8; 32];").unwrap();
    writeln!(out, "            padded[..len].copy_from_slice(&seed[..len]);").unwrap();
    writeln!(out, "            hasher.update(&padded);").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "        Ok(hasher.finalize().into())").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out, "#[allow(dead_code)]").unwrap();
    writeln!(out, "fn compute_pda_with_program(program_id: &ProgramId, seeds: &[&[u8]]) -> Result<AccountId, String> {{").unwrap();
    writeln!(out, "    Ok(AccountId::for_public_pda(program_id, &PdaSeed::new(pda_seed_bytes(seeds)?)))").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // parse_program_id_hex
    writeln!(out, "fn parse_program_id_hex(s: &str) -> Result<ProgramId, String> {{").unwrap();
    writeln!(out, "    let s = s.trim_start_matches(\"0x\");").unwrap();
    writeln!(out, "    if s.len() != 64 {{ return Err(format!(\"program_id hex must be 64 chars, got {{}}\", s.len())); }}").unwrap();
    writeln!(out, "    let bytes = hex::decode(s).map_err(|e| format!(\"invalid hex: {{}}\", e))?;").unwrap();
    writeln!(out, "    let mut pid = [0u32; 8];").unwrap();
    writeln!(out, "    for (i, chunk) in bytes.chunks(4).enumerate() {{").unwrap();
    writeln!(out, "        pid[i] = u32::from_le_bytes(chunk.try_into().unwrap());").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    Ok(pid)").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // parse_program_id (alias for ProgramId-typed args)
    writeln!(out, "fn parse_program_id(s: &str) -> Result<ProgramId, String> {{").unwrap();
    writeln!(out, "    parse_program_id_hex(s)").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // parse_account_id
    writeln!(out, "fn parse_account_id(s: &str) -> Result<AccountId, String> {{").unwrap();
    writeln!(out, "    let raw = s;\n    let s = s.strip_prefix(\"Public/\").or_else(|| s.strip_prefix(\"Private/\")).unwrap_or(s);").unwrap();
    writeln!(out, "    if let Ok(id) = s.parse() {{ return Ok(id); }}").unwrap();
    writeln!(out, "    let s = s.trim_start_matches(\"0x\");").unwrap();
    writeln!(out, "    if s.len() == 64 {{").unwrap();
    writeln!(out, "        let bytes = hex::decode(s).map_err(|e| format!(\"invalid hex: {{}}\", e))?;").unwrap();
    writeln!(out, "        let mut arr = [0u8; 32]; arr.copy_from_slice(&bytes);").unwrap();
    writeln!(out, "        return Ok(AccountId::new(arr));").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    Err(format!(\"invalid AccountId: {{}}\", raw))").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // parse_bytes32 — same inputs as parse_account_id but returns the raw [u8; 32].
    // Used for IDL fields typed [u8; 32] (PDA seed bytes, keys stored as raw arrays).
    writeln!(out, "fn parse_bytes32(s: &str) -> Result<[u8; 32], String> {{").unwrap();
    writeln!(out, "    let raw = s;").unwrap();
    writeln!(out, "    let s = s.strip_prefix(\"Public/\").or_else(|| s.strip_prefix(\"Private/\")).unwrap_or(s);").unwrap();
    writeln!(out, "    let s = s.trim_start_matches(\"0x\");").unwrap();
    writeln!(out, "    if s.len() == 64 {{").unwrap();
    writeln!(out, "        let bytes = hex::decode(s).map_err(|e| format!(\"invalid hex: {{}}\", e))?;").unwrap();
    writeln!(out, "        let mut arr = [0u8; 32]; arr.copy_from_slice(&bytes);").unwrap();
    writeln!(out, "        return Ok(arr);").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    if let Ok(id) = s.parse::<AccountId>() {{").unwrap();
    writeln!(out, "        let mut arr = [0u8; 32]; arr.copy_from_slice(id.as_ref());").unwrap();
    writeln!(out, "        return Ok(arr);").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    Err(format!(\"invalid [u8; 32]: {{}}\", raw))").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Shared async runtime — created once per process, reused across all FFI calls.
    writeln!(out, "static ASYNC_RUNTIME: std::sync::OnceLock<tokio::runtime::Runtime> = std::sync::OnceLock::new();").unwrap();
    writeln!(out, "fn get_runtime() -> &'static tokio::runtime::Runtime {{").unwrap();
    writeln!(out, "    ASYNC_RUNTIME.get_or_init(|| tokio::runtime::Runtime::new().expect(\"failed to create Tokio runtime\"))").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Global mutex to serialise env-var mutation + wallet init across FFI threads.
    // std::env::set_var is not thread-safe on its own; all FFI entry points that
    // call init_wallet hold this lock for the duration of the mutation + WalletCore
    // construction so they cannot race on NSSA_WALLET_HOME_DIR / NSSA_SEQUENCER_URL.
    writeln!(out, "static WALLET_INIT_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "fn init_wallet(v: &Value) -> Result<WalletCore, String> {{").unwrap();
    writeln!(out, "    let _guard = WALLET_INIT_LOCK.lock().map_err(|_| \"wallet lock poisoned\".to_string())?;").unwrap();
    writeln!(out, "    let wallet_path = v[\"wallet_path\"].as_str().ok_or(\"missing required field: wallet_path\")?;").unwrap();
    writeln!(out, "    if wallet_path.is_empty() || wallet_path.contains('\\0') {{").unwrap();
    writeln!(out, "        return Err(\"wallet_path must be a non-empty path without null bytes\".into());").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    let sequencer_url = v[\"sequencer_url\"].as_str().ok_or(\"missing required field: sequencer_url\")?;").unwrap();
    writeln!(out, "    std::env::set_var(\"NSSA_WALLET_HOME_DIR\", wallet_path);").unwrap();
    writeln!(out, "    std::env::set_var(\"NSSA_SEQUENCER_URL\", sequencer_url);").unwrap();
    writeln!(out, "    WalletCore::from_env().map_err(|e| format!(\"wallet init: {{}}\", e))").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Per-instruction FFI functions
    for ix in &idl.instructions {
        let fn_name = format!("{}_{}", prefix, snake_case(&ix.name));
        let variant = pascal_case(&ix.name);
        let signer_accounts: Vec<&IdlAccountItem> = ix.accounts.iter().filter(|a| a.signer).collect();

        writeln!(out, "/// FFI: {} instruction.", ix.name).unwrap();
        writeln!(out, "#[no_mangle]").unwrap();
        writeln!(out, "pub extern \"C\" fn {fn_name}(args_json: *const c_char) -> *mut c_char {{").unwrap();
        writeln!(out, "    let args = match cstr_to_str(args_json) {{").unwrap();
        writeln!(out, "        Ok(s) => s, Err(e) => return error_json(&e),").unwrap();
        writeln!(out, "    }};").unwrap();
        writeln!(out, "    ffi_call(move || {fn_name}_impl(args))").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "fn {fn_name}_impl(args: &str) -> Result<String, String> {{").unwrap();
        writeln!(out, "    let v: Value = serde_json::from_str(args).map_err(|e| format!(\"invalid JSON: {{}}\", e))?;").unwrap();
        writeln!(out, "    let program_id = parse_program_id_hex(v[\"program_id_hex\"].as_str().ok_or(\"missing program_id_hex\")?)?;").unwrap();
        writeln!(out, "    let wallet = init_wallet(&v)?;").unwrap();
        writeln!(out).unwrap();

        // Parse args
        for arg in &ix.args {
            let name = rust_ident(&arg.name);
            let parse_expr = idl_type_to_json_parse(&arg.type_, &format!("v[\"{}\"]", arg.name));
            writeln!(out, "    let {name} = {parse_expr};").unwrap();
        }
        writeln!(out).unwrap();

        // Build a type map for PDA seed arg type checks (same pattern as generate_pda_helpers)
        let param_type_map: std::collections::HashMap<String, String> = ix.args.iter()
            .map(|a| (rust_ident(&a.name), idl_type_to_rust(&a.type_)))
            .collect();

        // Resolve accounts in two passes so that PDA accounts whose seeds reference
        // other accounts (IdlSeed::Account) always find those accounts already bound.
        // Pass 1: non-PDA accounts (plain addresses and rest arrays).
        for acc in &ix.accounts {
            let name = rust_ident(&acc.name);
            if acc.rest {
                // If there's a Vec<[u8;32]> arg, derive rest accounts from it when the
                // JSON field is absent — the UI sends keys only once (as the instruction arg).
                let src_arg = ix.args.iter().find(|a| is_vec_bytes32(&a.type_));
                if let Some(src) = src_arg {
                    let src_name = rust_ident(&src.name);
                    writeln!(out, "    let {name}: Vec<AccountId> = if v[\"{}\"].is_array() {{", acc.name).unwrap();
                    writeln!(out, "        v[\"{}\"].as_array().unwrap()", acc.name).unwrap();
                    writeln!(out, "            .iter().map(|a| parse_account_id(a.as_str().ok_or(\"expected string\")?)).collect::<Result<Vec<_>,_>>()?").unwrap();
                    writeln!(out, "    }} else {{").unwrap();
                    writeln!(out, "        {src_name}.iter().map(|m| AccountId::new(*m)).collect()").unwrap();
                    writeln!(out, "    }};").unwrap();
                } else {
                    writeln!(out, "    let {name}: Vec<AccountId> = v[\"{}\"].as_array()", acc.name).unwrap();
                    writeln!(out, "        .ok_or(\"missing {}\")?", acc.name).unwrap();
                    writeln!(out, "        .iter().map(|a| parse_account_id(a.as_str().ok_or(\"expected string\")?)).collect::<Result<Vec<_>,_>>()?;").unwrap();
                }
            } else if acc.pda.is_none() {
                writeln!(out, "    let {name} = parse_account_id(v[\"{}\"].as_str().ok_or(\"missing {}\")?)?;",
                    acc.name, acc.name).unwrap();
            }
        }
        // Pass 2: PDA accounts (may reference accounts bound in pass 1).
        for acc in &ix.accounts {
            let name = rust_ident(&acc.name);
            if let Some(pda) = &acc.pda {
                // Collect pre-bindings (stable buffers for types that can't be borrowed
                // as a slice element inline) and seed entries separately, then emit.
                let mut seed_pre_bindings: Vec<String> = Vec::new();
                let mut seed_entries: Vec<String> = Vec::new();
                for seed in &pda.seeds {
                    match seed {
                        IdlSeed::Const { value } => seed_entries.push(format!("        b\"{value}\",")),
                        IdlSeed::Account { path } => seed_entries.push(format!("        {}.as_ref(),", rust_ident(path))),
                        IdlSeed::Arg { path } => {
                            let pname = rust_ident(path);
                            let arg_ty = param_type_map.get(&pname).map(|s| s.as_str()).unwrap_or("");
                            match arg_ty {
                                "[u8; 32]" | "[u8;32]" | "AccountId" | "account_id" => {
                                    seed_entries.push(format!("        {pname}.as_ref(),"));
                                }
                                "[u32; 8]" | "[u32;8]" | "ProgramId" => {
                                    // collect() into a Vec to avoid a reference to a temporary
                                    seed_pre_bindings.push(format!("    let {pname}_seed_bytes: Vec<u8> = {pname}.iter().flat_map(|w| w.to_le_bytes()).collect();"));
                                    seed_entries.push(format!("        &{pname}_seed_bytes,"));
                                }
                                "u64" | "u32" | "u16" | "u8" | "i64" | "i32" | "i16" | "i8" | "u128" | "i128" => {
                                    seed_pre_bindings.push(format!("    let {pname}_seed_bytes = {pname}.to_le_bytes();"));
                                    seed_entries.push(format!("        &{pname}_seed_bytes,"));
                                }
                                "String" | "string" | "&str" => {
                                    seed_entries.push(format!("        {pname}.as_bytes(),"));
                                }
                                _ => seed_entries.push(format!("        {pname}.as_ref(),")),
                            }
                        }
                    }
                }
                for binding in &seed_pre_bindings {
                    writeln!(out, "{binding}").unwrap();
                }
                writeln!(out, "    let {name} = compute_pda_with_program(&program_id, &[").unwrap();
                for entry in &seed_entries {
                    writeln!(out, "{entry}").unwrap();
                }
                writeln!(out, "    ])?;").unwrap();
            }
        }
        writeln!(out).unwrap();

        // Build account_ids vec (non-rest accounts first, then rest)
        let has_rest = ix.accounts.iter().any(|a| a.rest);
        let account_ids_binding = if has_rest { "let mut" } else { "let" };
        writeln!(out, "    {account_ids_binding} account_ids: Vec<AccountId> = vec![").unwrap();
        for acc in ix.accounts.iter().filter(|a| !a.rest) {
            writeln!(out, "        {},", rust_ident(&acc.name)).unwrap();
        }
        writeln!(out, "    ];").unwrap();
        for acc in ix.accounts.iter().filter(|a| a.rest) {
            writeln!(out, "    account_ids.extend({});", rust_ident(&acc.name)).unwrap();
        }

        // Signer IDs
        writeln!(out, "    let signer_ids: Vec<AccountId> = vec![").unwrap();
        for acc in &signer_accounts {
            writeln!(out, "        {},", rust_ident(&acc.name)).unwrap();
        }
        writeln!(out, "    ];").unwrap();
        writeln!(out).unwrap();

        // Build instruction
        if ix.args.is_empty() {
            writeln!(out, "    let instruction = {instr_type}::{variant};").unwrap();
        } else {
            writeln!(out, "    let instruction = {instr_type}::{variant} {{").unwrap();
            for arg in &ix.args {
                let name = rust_ident(&arg.name);
                writeln!(out, "        {name},").unwrap();
            }
            writeln!(out, "    }};").unwrap();
        }
        writeln!(out).unwrap();

        // Submit via the shared runtime
        writeln!(out, "    let rt = get_runtime();").unwrap();
        writeln!(out, "    let tx_hash = rt.block_on(async {{").unwrap();
        writeln!(out, "        let nonces = wallet.get_accounts_nonces(signer_ids.clone()).await").unwrap();
        writeln!(out, "            .map_err(|e| format!(\"nonces: {{}}\", e))?;").unwrap();
        writeln!(out, "        let mut signing_keys = Vec::new();").unwrap();
        writeln!(out, "        for sid in &signer_ids {{").unwrap();
        writeln!(out, "            let key = wallet.storage().user_data").unwrap();
        writeln!(out, "                .get_pub_account_signing_key(*sid)").unwrap();
        writeln!(out, "                .ok_or_else(|| format!(\"signing key not found for {{}}\", sid))?;").unwrap();
        writeln!(out, "            signing_keys.push(key);").unwrap();
        writeln!(out, "        }}").unwrap();
        writeln!(out, "        let message = Message::try_new(program_id, account_ids, nonces, instruction)").unwrap();
        writeln!(out, "            .map_err(|e| format!(\"message: {{:?}}\", e))?;").unwrap();
        writeln!(out, "        let witness_set = WitnessSet::for_message(&message, &signing_keys);").unwrap();
        writeln!(out, "        let tx = PublicTransaction::new(message, witness_set);").unwrap();
        writeln!(out, "        let raw = wallet.sequencer_client.send_transaction(common::transaction::NSSATransaction::Public(tx)).await").unwrap();
        writeln!(out, "            .map_err(|e| format!(\"submit: {{}}\", e))?;").unwrap();
        writeln!(out, "        let tx_hash_hex = hex::encode(raw.0);").unwrap();
        writeln!(out, "        let poller = wallet::poller::TxPoller::new(wallet.config(), wallet.sequencer_client.clone());").unwrap();
        writeln!(out, "        poller.poll_tx(raw).await.map_err(|e| format!(\"confirm: {{}}\", e))?;").unwrap();
        writeln!(out, "        Ok::<String, String>(tx_hash_hex)").unwrap();
        writeln!(out, "    }})?;").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "    Ok(json!({{\"success\": true, \"tx_hash\": tx_hash}}).to_string())").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    // free + version
    writeln!(out, "#[no_mangle]").unwrap();
    writeln!(out, "pub extern \"C\" fn {prefix}_free_string(s: *mut c_char) {{").unwrap();
    writeln!(out, "    if !s.is_null() {{ unsafe {{ drop(CString::from_raw(s)) }}; }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#[no_mangle]").unwrap();
    writeln!(out, "pub extern \"C\" fn {prefix}_version() -> *mut c_char {{").unwrap();
    writeln!(out, "    to_cstring(\"{}\".to_string())", idl.version).unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    // program_id: locate the guest binary and compute its ProgramId via nssa::program::Program.
    // Tries the standard project-relative path first, then walks up ancestor directories
    // so it works whether the process cwd is the project root or a build subdirectory.
    writeln!(out, "#[no_mangle]").unwrap();
    writeln!(out, "pub extern \"C\" fn {prefix}_program_id() -> *mut c_char {{").unwrap();
    writeln!(out, "    let rel = \"methods/guest/target/riscv32im-risc0-zkvm-elf/docker/{prefix}.bin\";").unwrap();
    writeln!(out, "    let data = std::env::current_dir().ok().and_then(|cwd| {{").unwrap();
    writeln!(out, "        cwd.ancestors().take(6).find_map(|dir| std::fs::read(dir.join(rel)).ok())").unwrap();
    writeln!(out, "    }});").unwrap();
    writeln!(out, "    let data = match data {{ Some(d) => d, None => return std::ptr::null_mut() }};").unwrap();
    writeln!(out, "    let program = match Program::new(data) {{ Ok(p) => p, Err(_) => return std::ptr::null_mut() }};").unwrap();
    writeln!(out, "    let id = program.id();").unwrap();
    writeln!(out, "    let hex: String = id.iter().flat_map(|w| w.to_le_bytes()).map(|b| format!(\"{{:02x}}\", b)).collect();").unwrap();
    out.push_str("    let json = json!({\"program_id_hex\": hex}).to_string();\n");
    writeln!(out, "    CString::new(json).map(|cs| cs.into_raw()).unwrap_or(std::ptr::null_mut())").unwrap();
    writeln!(out, "}}").unwrap();

    // Wallet connectivity helpers (always generated, not per-IDL)
    writeln!(out).unwrap();
    writeln!(out, "/// FFI: ping the sequencer to verify wallet + network connectivity.").unwrap();
    writeln!(out, "#[no_mangle]").unwrap();
    writeln!(out, "pub extern \"C\" fn {prefix}_check_connection(args_json: *const c_char) -> *mut c_char {{").unwrap();
    writeln!(out, "    let args = match cstr_to_str(args_json) {{ Ok(s) => s, Err(e) => return error_json(&e) }};").unwrap();
    writeln!(out, "    ffi_call(move || {prefix}_check_connection_impl(args))").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "fn {prefix}_check_connection_impl(args: &str) -> Result<String, String> {{").unwrap();
    writeln!(out, "    let v: Value = serde_json::from_str(args).map_err(|e| format!(\"invalid JSON: {{}}\", e))?;").unwrap();
    writeln!(out, "    let sequencer_url = v[\"sequencer_url\"].as_str().ok_or(\"missing sequencer_url\")?.to_string();").unwrap();
    writeln!(out, "    let wallet = init_wallet(&v)?;").unwrap();
    writeln!(out, "    let rt = get_runtime();").unwrap();
    writeln!(out, "    rt.block_on(async {{").unwrap();
    writeln!(out, "        wallet.get_accounts_nonces(vec![]).await.map_err(|e| format!(\"ping: {{}}\", e))").unwrap();
    writeln!(out, "    }})?;").unwrap();
    writeln!(out, "    Ok(json!({{\"success\": true, \"status\": \"ok\", \"sequencer_url\": sequencer_url}}).to_string())").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "/// FFI: inspect an account — returns data size, hex preview, and signing-key presence.").unwrap();
    writeln!(out, "#[no_mangle]").unwrap();
    writeln!(out, "pub extern \"C\" fn {prefix}_inspect_account(args_json: *const c_char) -> *mut c_char {{").unwrap();
    writeln!(out, "    let args = match cstr_to_str(args_json) {{ Ok(s) => s, Err(e) => return error_json(&e) }};").unwrap();
    writeln!(out, "    ffi_call(move || {prefix}_inspect_account_impl(args))").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "fn {prefix}_inspect_account_impl(args: &str) -> Result<String, String> {{").unwrap();
    writeln!(out, "    let v: Value = serde_json::from_str(args).map_err(|e| format!(\"invalid JSON: {{}}\", e))?;").unwrap();
    writeln!(out, "    let wallet = init_wallet(&v)?;").unwrap();
    writeln!(out, "    let account_id = parse_account_id(v[\"account_id\"].as_str().ok_or(\"missing account_id\")?)?;").unwrap();
    writeln!(out, "    let rt = get_runtime();").unwrap();
    writeln!(out, "    let account = rt.block_on(async {{").unwrap();
    writeln!(out, "        wallet.sequencer_client.get_account(account_id).await.map_err(|e| format!(\"get_account: {{}}\", e))").unwrap();
    writeln!(out, "    }})?;").unwrap();
    writeln!(out, "    let has_key = wallet.storage().user_data.get_pub_account_signing_key(account_id).is_some();").unwrap();
    writeln!(out, "    let data_len = account.data.len();").unwrap();
    writeln!(out, "    let preview_len = data_len.min(32);").unwrap();
    writeln!(out, "    let data_preview = hex::encode(&account.data[..preview_len]);").unwrap();
    // program_owner classification
    writeln!(out, "    let owner_bytes: Vec<u8> = account.program_owner.iter().flat_map(|w| w.to_le_bytes()).collect();").unwrap();
    writeln!(out, "    let program_owner_hex = hex::encode(&owner_bytes);").unwrap();
    writeln!(out, "    let is_uninitialized = account.program_owner == [0u32; 8];").unwrap();
    writeln!(out, "    let maybe_program_id = v[\"program_id_hex\"].as_str()").unwrap();
    writeln!(out, "        .filter(|s| !s.is_empty())").unwrap();
    writeln!(out, "        .map(|s| parse_program_id_hex(s))").unwrap();
    writeln!(out, "        .transpose()?;").unwrap();
    writeln!(out, "    let status = if is_uninitialized {{ \"uninitialized\" }}").unwrap();
    writeln!(out, "        else if maybe_program_id.map_or(false, |pid| account.program_owner == pid) {{ \"owned\" }}").unwrap();
    writeln!(out, "        else {{ \"foreign\" }};").unwrap();
    writeln!(out, "    Ok(json!({{").unwrap();
    writeln!(out, "        \"success\": true, \"data_len\": data_len, \"data_preview\": data_preview,").unwrap();
    writeln!(out, "        \"has_signing_key\": has_key, \"program_owner\": program_owner_hex, \"status\": status").unwrap();
    writeln!(out, "    }}).to_string())").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Wallet CLI subprocess helpers
    // TEMPORARY: until LEZ exposes account listing/creation via the wallet library API,
    // these call the `wallet` CLI binary directly.  Remove once the native API exists.
    writeln!(out, "/// FFI: list accounts in the wallet — delegates to `wallet account list --json`.").unwrap();
    writeln!(out, "/// TEMPORARY: uses `wallet` CLI subprocess until the library API is available.").unwrap();
    writeln!(out, "#[no_mangle]").unwrap();
    writeln!(out, "pub extern \"C\" fn {prefix}_list_accounts(args_json: *const c_char) -> *mut c_char {{").unwrap();
    writeln!(out, "    let args = match cstr_to_str(args_json) {{ Ok(s) => s, Err(e) => return error_json(&e) }};").unwrap();
    writeln!(out, "    ffi_call(move || {prefix}_list_accounts_impl(args))").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "fn {prefix}_list_accounts_impl(args: &str) -> Result<String, String> {{").unwrap();
    writeln!(out, "    let v: Value = serde_json::from_str(args).map_err(|e| format!(\"invalid JSON: {{}}\", e))?;").unwrap();
    writeln!(out, "    let wallet_path = v[\"wallet_path\"].as_str().ok_or(\"missing wallet_path\")?;").unwrap();
    writeln!(out, "    if wallet_path.is_empty() || wallet_path.contains('\\0') {{").unwrap();
    writeln!(out, "        return Err(\"wallet_path must be a non-empty path without null bytes\".into());").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    let output = std::process::Command::new(\"wallet\")").unwrap();
    writeln!(out, "        .args([\"account\", \"list\"])").unwrap();
    writeln!(out, "        .env(\"NSSA_WALLET_HOME_DIR\", wallet_path)").unwrap();
    writeln!(out, "        .output()").unwrap();
    writeln!(out, "        .map_err(|e| format!(\"wallet CLI: {{}}\", e))?;").unwrap();
    writeln!(out, "    if !output.status.success() {{").unwrap();
    writeln!(out, "        let stderr = String::from_utf8_lossy(&output.stderr);").unwrap();
    writeln!(out, "        return Err(format!(\"wallet account list: {{}}\", stderr.trim()));").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    let stdout = String::from_utf8_lossy(&output.stdout);").unwrap();
    writeln!(out, "    // Output format per line: `{{path}} {{Public|Private}}/{{id}} [optional-tag]`").unwrap();
    writeln!(out, "    let raw: Vec<(String, String, String)> = stdout.lines()").unwrap();
    writeln!(out, "        .filter_map(|line| {{").unwrap();
    writeln!(out, "            let id = line.split_whitespace()").unwrap();
    writeln!(out, "                .find(|s| s.starts_with(\"Public/\") || s.starts_with(\"Private/\"))?;").unwrap();
    writeln!(out, "            let label = line.split_whitespace()").unwrap();
    writeln!(out, "                .find(|s| s.starts_with('[') && s.ends_with(']'))").unwrap();
    writeln!(out, "                .map(|s| s.trim_matches(|c: char| c == '[' || c == ']').to_string())").unwrap();
    writeln!(out, "                .unwrap_or_default();").unwrap();
    writeln!(out, "            let path = line.trim_end()").unwrap();
    writeln!(out, "                .split(id).next().unwrap_or(\"\").trim().to_string();").unwrap();
    writeln!(out, "            Some((id.to_string(), label, path))").unwrap();
    writeln!(out, "        }})").unwrap();
    writeln!(out, "        .collect();").unwrap();
    writeln!(out).unwrap();
    // Classify accounts via sequencer if available
    writeln!(out, "    // Classify each account (owner → uninitialized / owned / foreign).").unwrap();
    writeln!(out, "    // Falls back to status \"unknown\" when sequencer is unreachable.").unwrap();
    writeln!(out, "    let maybe_wallet = init_wallet(&v).ok();").unwrap();
    writeln!(out, "    let maybe_program_id = v[\"program_id_hex\"].as_str()").unwrap();
    writeln!(out, "        .filter(|s| !s.is_empty())").unwrap();
    writeln!(out, "        .and_then(|s| parse_program_id_hex(s).ok());").unwrap();
    writeln!(out, "    let rt = get_runtime();").unwrap();
    writeln!(out, "    let accounts: Vec<serde_json::Value> = rt.block_on(async {{").unwrap();
    writeln!(out, "        let mut result = Vec::new();").unwrap();
    writeln!(out, "        for (id, label, path) in &raw {{").unwrap();
    writeln!(out, "            // Strip \"Public/\" or \"Private/\" prefix before parsing").unwrap();
    writeln!(out, "            let raw_id = id.split('/').last().unwrap_or(id.as_str());").unwrap();
    writeln!(out, "            let status = if let (Some(wallet), Ok(aid)) = (&maybe_wallet, parse_account_id(raw_id)) {{").unwrap();
    writeln!(out, "                match wallet.sequencer_client.get_account(aid).await {{").unwrap();
    writeln!(out, "                    Ok(account) => {{").unwrap();
    writeln!(out, "                        let is_uninit = account.program_owner == [0u32; 8];").unwrap();
    writeln!(out, "                        if is_uninit {{ \"uninitialized\" }}").unwrap();
    writeln!(out, "                        else if maybe_program_id.map_or(false, |pid| account.program_owner == pid) {{ \"owned\" }}").unwrap();
    writeln!(out, "                        else {{ \"foreign\" }}").unwrap();
    writeln!(out, "                    }}").unwrap();
    writeln!(out, "                    Err(_) => \"unknown\",").unwrap();
    writeln!(out, "                }}").unwrap();
    writeln!(out, "            }} else {{ \"unknown\" }};").unwrap();
    writeln!(out, "            result.push(json!({{\"id\": id, \"label\": label, \"path\": path, \"status\": status}}));").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "        result").unwrap();
    writeln!(out, "    }});").unwrap();
    writeln!(out, "    Ok(json!({{\"success\": true, \"accounts\": accounts}}).to_string())").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "/// FFI: create a new public account — delegates to `wallet account new public`.").unwrap();
    writeln!(out, "/// TEMPORARY: uses `wallet` CLI subprocess until the library API is available.").unwrap();
    writeln!(out, "#[no_mangle]").unwrap();
    writeln!(out, "pub extern \"C\" fn {prefix}_create_account(args_json: *const c_char) -> *mut c_char {{").unwrap();
    writeln!(out, "    let args = match cstr_to_str(args_json) {{ Ok(s) => s, Err(e) => return error_json(&e) }};").unwrap();
    writeln!(out, "    ffi_call(move || {prefix}_create_account_impl(args))").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "fn {prefix}_create_account_impl(args: &str) -> Result<String, String> {{").unwrap();
    writeln!(out, "    let v: Value = serde_json::from_str(args).map_err(|e| format!(\"invalid JSON: {{}}\", e))?;").unwrap();
    writeln!(out, "    let wallet_path = v[\"wallet_path\"].as_str().ok_or(\"missing wallet_path\")?;").unwrap();
    writeln!(out, "    if wallet_path.is_empty() || wallet_path.contains('\\0') {{").unwrap();
    writeln!(out, "        return Err(\"wallet_path must be a non-empty path without null bytes\".into());").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    let mut cmd = std::process::Command::new(\"wallet\");").unwrap();
    writeln!(out, "    cmd.args([\"account\", \"new\", \"public\"]);").unwrap();
    writeln!(out, "    if let Some(label) = v[\"label\"].as_str().filter(|s| !s.is_empty()) {{").unwrap();
    writeln!(out, "        cmd.args([\"--label\", label]);").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    let output = cmd.env(\"NSSA_WALLET_HOME_DIR\", wallet_path)").unwrap();
    writeln!(out, "        .output()").unwrap();
    writeln!(out, "        .map_err(|e| format!(\"wallet CLI: {{}}\", e))?;").unwrap();
    writeln!(out, "    let stdout = String::from_utf8_lossy(&output.stdout).trim().to_string();").unwrap();
    writeln!(out, "    let stderr = String::from_utf8_lossy(&output.stderr).trim().to_string();").unwrap();
    writeln!(out, "    if !output.status.success() {{").unwrap();
    writeln!(out, "        return Err(format!(\"wallet account new: {{}}\", if stderr.is_empty() {{ &stdout }} else {{ &stderr }}));").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    // stdout from `wallet account new public` is the new account ID").unwrap();
    writeln!(out, "    Ok(json!({{\"success\": true, \"account_id\": stdout}}).to_string())").unwrap();
    writeln!(out, "}}").unwrap();

    // decode_account: fetches raw data and tries each IDL account type via spel_framework_core::decode
    writeln!(out).unwrap();
    writeln!(out, "/// FFI: decode an account's data against each known IDL type, returning the first match.").unwrap();
    writeln!(out, "#[no_mangle]").unwrap();
    writeln!(out, "pub extern \"C\" fn {prefix}_decode_account(args_json: *const c_char) -> *mut c_char {{").unwrap();
    writeln!(out, "    let args = match cstr_to_str(args_json) {{ Ok(s) => s, Err(e) => return error_json(&e) }};").unwrap();
    writeln!(out, "    ffi_call(move || {prefix}_decode_account_impl(args))").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "fn {prefix}_decode_account_impl(args: &str) -> Result<String, String> {{").unwrap();
    writeln!(out, "    let v: Value = serde_json::from_str(args).map_err(|e| format!(\"invalid JSON: {{}}\", e))?;").unwrap();
    writeln!(out, "    let wallet = init_wallet(&v)?;").unwrap();
    writeln!(out, "    let account_id = parse_account_id(v[\"account_id\"].as_str().ok_or(\"missing account_id\")?)?;").unwrap();
    writeln!(out, "    let rt = get_runtime();").unwrap();
    writeln!(out, "    let account = rt.block_on(async {{").unwrap();
    writeln!(out, "        wallet.sequencer_client.get_account(account_id).await.map_err(|e| format!(\"get_account: {{}}\", e))").unwrap();
    writeln!(out, "    }})?;").unwrap();
    writeln!(out, "    if account.data.is_empty() {{").unwrap();
    writeln!(out, "        return Ok(json!({{\"success\": true, \"status\": \"uninitialized\", \"type\": null, \"fields\": null}}).to_string());").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    let idl: spel_framework_core::idl::SpelIdl = serde_json::from_str(PROGRAM_IDL_JSON)").unwrap();
    writeln!(out, "        .map_err(|e| format!(\"IDL parse: {{}}\", e))?;").unwrap();
    writeln!(out, "    match spel_framework_core::decode::decode_account_data_try_all(&account.data, &idl) {{").unwrap();
    writeln!(out, "        Some((type_name, fields)) => Ok(json!({{\"success\": true, \"type\": type_name, \"fields\": fields}}).to_string()),").unwrap();
    writeln!(out, "        None => Ok(json!({{\"success\": true, \"type\": null, \"fields\": null, \"raw_hex\": hex::encode(&account.data)}}).to_string()),").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();

    // PDA compute helpers
    out.push_str(&generate_pda_helpers(idl));

    // Named IDL types (enums, structs) referenced by account fields
    generate_defined_types(idl, &mut out);

    // Account state structs (BorshDeserialize)
    generate_account_types(idl, &mut out);

    // Fetch functions
    generate_account_fetch_functions(idl, &prefix, &mut out);

    Ok(out)
}

/// Generate standalone PDA compute helper functions from an IDL.
///
/// Emits one `pub fn compute_{account}_pda(...)` per unique account that has
/// a `pda` field in the IDL. The generated functions use SHA-256 to combine
/// multiple seeds (matching `spel-cli/src/pda.rs` behaviour) and return an
/// `AccountId` derived from the program ID and the combined seed.
pub fn generate_pda_helpers(idl: &SpelIdl) -> String {
    use std::collections::HashSet;
    let mut out = String::new();
    let mut seen: HashSet<String> = HashSet::new();

    for ix in &idl.instructions {
        for acc in &ix.accounts {
            let acc_name = snake_case(&acc.name);
            if let Some(pda) = &acc.pda {
                if !seen.insert(acc_name.clone()) {
                    continue; // already generated for this account name
                }

                // Collect function parameters from arg seeds.
                // Const seeds are inlined; account seeds get a TODO comment.
                let mut params: Vec<(String, String)> = Vec::new();
                for seed in &pda.seeds {
                    match seed {
                        IdlSeed::Arg { path } => {
                            let ty = ix.args.iter().find(|a| a.name == *path)
                                .map(|a| idl_type_to_rust(&a.type_))
                                .unwrap_or_else(|| "[u8; 32]".to_string());
                            // Normalise aliases to raw array types for cleaner FFI signatures
                            let param_ty = match ty.as_str() {
                                "AccountId" => "[u8; 32]".to_string(),
                                "ProgramId" => "[u32; 8]".to_string(),
                                other => other.to_string(),
                            };
                            params.push((rust_ident(path), param_ty));
                        }
                        IdlSeed::Account { .. } => {
                            // account seeds: less common, skipped (see TODO inside generated fn)
                        }
                        IdlSeed::Const { .. } => {}
                    }
                }

                // Doc comment
                writeln!(out).unwrap();
                let seed_desc: Vec<String> = pda.seeds.iter().map(|s| match s {
                    IdlSeed::Const { value } => format!("const(\"{}\")", value),
                    IdlSeed::Arg { path } => format!("arg({})", path),
                    IdlSeed::Account { path } => format!("account({})", path),
                }).collect();
                writeln!(out, "/// Compute PDA for `{}` account.", acc.name).unwrap();
                writeln!(out, "/// Seeds: [{}]", seed_desc.join(", ")).unwrap();

                // Build a type map for seed loops to look up arg types
                let param_type_map: std::collections::HashMap<String, String> =
                    params.iter().cloned().collect();

                // Function signature
                write!(out, "pub fn compute_{}_pda(", acc_name).unwrap();
                write!(out, "program_id: &ProgramId").unwrap();
                for (name, ty) in &params {
                    // Primitive scalars (u64, u32, etc.) are passed by value
                    let is_scalar = matches!(ty.as_str(), "u64" | "u32" | "u16" | "u8" | "i64" | "i32" | "i16" | "i8" | "u128" | "i128");
                    if is_scalar {
                        write!(out, ", {}: {}", name, ty).unwrap();
                    } else {
                        write!(out, ", {}: &{}", name, ty).unwrap();
                    }
                }
                writeln!(out, ") -> AccountId {{").unwrap();

                let n_seeds = pda.seeds.len();
                if n_seeds == 1 {
                    // Single seed: use directly as PdaSeed bytes
                    match &pda.seeds[0] {
                        IdlSeed::Const { value } => {
                            writeln!(out, "    let mut seed_bytes = [0u8; 32];").unwrap();
                            writeln!(out, "    let src = b\"{}\";", value).unwrap();
                            writeln!(out, "    seed_bytes[..src.len()].copy_from_slice(src);").unwrap();
                        }
                        IdlSeed::Arg { path } => {
                            let pname = rust_ident(path);
                            let arg_ty = param_type_map.get(&pname).map(|s| s.as_str()).unwrap_or("");
                            if arg_ty == "u64" {
                                // u64 single seed: pad little-endian bytes into [u8; 32]
                                writeln!(out, "    let mut seed_bytes = [0u8; 32];").unwrap();
                                writeln!(out, "    seed_bytes[..8].copy_from_slice(&{}.to_le_bytes());", pname).unwrap();
                            } else {
                                writeln!(out, "    let seed_bytes: [u8; 32] = *{};", pname).unwrap();
                            }
                        }
                        IdlSeed::Account { path } => {
                            let pname = rust_ident(path);
                            writeln!(out, "    // TODO: account seed '{}' — pass the raw AccountId bytes here", path).unwrap();
                            writeln!(out, "    let seed_bytes: [u8; 32] = *{};", pname).unwrap();
                        }
                    }
                    writeln!(out, "    let pda_seed = nssa_core::program::PdaSeed::new(seed_bytes);").unwrap();
                    writeln!(out, "    AccountId::for_public_pda(program_id, &pda_seed)").unwrap();
                } else {
                    // Multi-seed: SHA-256(seed1 || seed2 || ...) — matches spel-cli/src/pda.rs
                    writeln!(out, "    use sha2::{{Sha256, Digest}};").unwrap();
                    writeln!(out, "    let mut hasher = Sha256::new();").unwrap();
                    for seed in &pda.seeds {
                        match seed {
                            IdlSeed::Const { value } => {
                                writeln!(out, "    {{").unwrap();
                                writeln!(out, "        let mut padded = [0u8; 32];").unwrap();
                                writeln!(out, "        let src = b\"{}\";", value).unwrap();
                                writeln!(out, "        padded[..src.len()].copy_from_slice(src);").unwrap();
                                writeln!(out, "        hasher.update(&padded);").unwrap();
                                writeln!(out, "    }}").unwrap();
                            }
                            IdlSeed::Arg { path } => {
                                let pname = rust_ident(path);
                                let arg_ty = param_type_map.get(&pname).map(|s| s.as_str()).unwrap_or("");
                                if arg_ty == "u64" {
                                    // u64 seed: hash the little-endian bytes directly
                                    writeln!(out, "    hasher.update(&{}.to_le_bytes());", pname).unwrap();
                                } else {
                                    writeln!(out, "    hasher.update({} as &[u8]);", pname).unwrap();
                                }
                            }
                            IdlSeed::Account { path } => {
                                let pname = rust_ident(path);
                                writeln!(out, "    // TODO: account seed '{}' — use account bytes", path).unwrap();
                                writeln!(out, "    hasher.update({} as &[u8]);", pname).unwrap();
                            }
                        }
                    }
                    writeln!(out, "    let combined: [u8; 32] = hasher.finalize().into();").unwrap();
                    writeln!(out, "    let pda_seed = nssa_core::program::PdaSeed::new(combined);").unwrap();
                    writeln!(out, "    AccountId::for_public_pda(program_id, &pda_seed)").unwrap();
                }
                writeln!(out, "}}").unwrap();
            }
        }
    }

    out
}

/// Returns true if the type (or any nested type) contains a `Defined` reference
/// that cannot be resolved in `known_types`.
fn has_unresolvable_defined_type(ty: &IdlType, known_types: &std::collections::HashSet<&str>) -> bool {
    use spel_framework_core::idl::IdlType;
    match ty {
        IdlType::Defined { defined } => !known_types.contains(defined.as_str()),
        IdlType::Vec { vec } => has_unresolvable_defined_type(vec, known_types),
        IdlType::Option { option } => has_unresolvable_defined_type(option, known_types),
        IdlType::Array { array: (elem, _) } => has_unresolvable_defined_type(elem, known_types),
        _ => false,
    }
}

/// Returns true if `acc_name` (snake_case) qualifies for fetch function generation:
/// it must have a matching struct entry in `idl.accounts` with non-empty fields and
/// all `Defined` field types resolvable in `idl.types`.
fn is_fetch_eligible(idl: &SpelIdl, acc_name: &str) -> bool {
    let known: std::collections::HashSet<&str> = idl.types.iter().map(|t| t.name.as_str()).collect();
    match idl.accounts.iter().find(|at| snake_case(&at.name) == acc_name) {
        None => false,
        Some(t) => {
            t.type_.kind == "struct"
                && !t.type_.fields.is_empty()
                && !t.type_.fields.iter().any(|f| has_unresolvable_defined_type(&f.type_, &known))
        }
    }
}

/// Emit Borsh-deserializable type definitions for all named types in `idl.types`.
/// These cover enums and structs referenced via `Defined { defined }` from account fields.
pub fn generate_defined_types(idl: &SpelIdl, out: &mut String) {
    for def in &idl.types {
        if def.name.is_empty() { continue; }
        let name = &def.name;
        writeln!(out).unwrap();
        writeln!(out, "/// Auto-generated Borsh type: `{name}`.").unwrap();
        writeln!(out, "#[allow(dead_code)]").unwrap();
        writeln!(out, "#[derive(borsh::BorshDeserialize)]").unwrap();
        if def.kind == "enum" {
            writeln!(out, "enum {name} {{").unwrap();
            for variant in &def.variants {
                if variant.fields.is_empty() {
                    writeln!(out, "    {},", variant.name).unwrap();
                } else {
                    let fields: String = variant.fields.iter()
                        .map(|f| format!("{}: {}", rust_ident(&f.name), idl_type_to_borsh_rust(&f.type_)))
                        .collect::<Vec<_>>()
                        .join(", ");
                    writeln!(out, "    {} {{ {fields} }},", variant.name).unwrap();
                }
            }
            writeln!(out, "}}").unwrap();
        } else if def.kind == "struct" {
            writeln!(out, "struct {name} {{").unwrap();
            for field in &def.fields {
                let fname = rust_ident(&field.name);
                let ftype = idl_type_to_borsh_rust(&field.type_);
                writeln!(out, "    pub {fname}: {ftype},").unwrap();
            }
            writeln!(out, "}}").unwrap();
        }
    }
}

/// Emit the Rust type for a struct field that will be BorshDeserialize'd.
fn idl_type_to_borsh_rust(ty: &IdlType) -> String {
    use spel_framework_core::idl::IdlType;
    match ty {
        IdlType::Primitive(p) => match p.as_str() {
            "account_id" | "AccountId" | "[u8; 32]" | "[u8;32]" => "[u8; 32]".to_string(),
            "program_id" | "ProgramId" | "[u32; 8]" | "[u32;8]" => "[u32; 8]".to_string(),
            "string" => "String".to_string(),
            s => s.to_string(),
        },
        IdlType::Vec { vec } => format!("Vec<{}>", idl_type_to_borsh_rust(vec)),
        IdlType::Option { option } => format!("Option<{}>", idl_type_to_borsh_rust(option)),
        IdlType::Defined { defined } => defined.clone(),
        IdlType::Array { array: (elem, size) } => {
            format!("[{}; {}]", idl_type_to_borsh_rust(elem), size)
        }
    }
}

/// For each entry in `idl.accounts` that qualifies for fetch, emit a BorshDeserialize struct.
/// Mirrors the iteration in `generate_account_fetch_functions` so every emitted fetch function
/// has a corresponding state struct.
pub fn generate_account_types(idl: &SpelIdl, out: &mut String) {
    for type_def in &idl.accounts {
        let acc_name = snake_case(&type_def.name);
        if !is_fetch_eligible(idl, &acc_name) { continue; }

        let pascal_name = pascal_case(&acc_name);
        writeln!(out).unwrap();
        writeln!(out, "/// Auto-generated Borsh state struct for `{acc_name}` account.").unwrap();
        writeln!(out, "#[derive(borsh::BorshDeserialize)]").unwrap();
        writeln!(out, "struct {pascal_name}State {{").unwrap();
        for field in &type_def.type_.fields {
            let fname = rust_ident(&field.name);
            let ftype = idl_type_to_borsh_rust(&field.type_);
            writeln!(out, "    pub {fname}: {ftype},").unwrap();
        }
        writeln!(out, "}}").unwrap();
    }
}

/// Generate `extern "C" fn {prefix}_fetch_{account}(args_json) -> *mut c_char` for each
/// unique PDA account (keyed by instruction parameter name). Decoding uses
/// `decode_account_data_try_all` so there is no type-name coupling.
pub fn generate_account_fetch_functions(idl: &SpelIdl, prefix: &str, out: &mut String) {
    use std::collections::HashSet;
    let mut seen: HashSet<String> = HashSet::new();

    for ix in &idl.instructions {
        for acc in &ix.accounts {
            let Some(pda) = &acc.pda else { continue };
            let acc_name = snake_case(&acc.name);
            if !seen.insert(acc_name.clone()) { continue; }

            let fn_name = format!("{prefix}_fetch_{acc_name}");

            let param_type_map: std::collections::HashMap<String, String> = ix.args.iter()
                .map(|a| (rust_ident(&a.name), idl_type_to_rust(&a.type_)))
                .collect();

            let mut seed_parse_lines: Vec<String> = Vec::new();
            let mut pda_seeds_code: Vec<String> = Vec::new();

            for seed in &pda.seeds {
                match seed {
                    IdlSeed::Const { value } => {
                        pda_seeds_code.push(format!("        b\"{value}\","));
                    }
                    IdlSeed::Arg { path } => {
                        let pname = rust_ident(path);
                        let arg_ty = param_type_map.get(&pname).map(|s| s.as_str()).unwrap_or("").to_string();
                        let parse_expr = idl_type_to_json_parse(
                            &ix.args.iter().find(|a| rust_ident(&a.name) == pname)
                                .map(|a| a.type_.clone())
                                .unwrap_or(spel_framework_core::idl::IdlType::Primitive("String".to_string())),
                            &format!("args[\"{path}\"]"));
                        seed_parse_lines.push(format!("        let {pname} = {parse_expr};"));
                        // Seed bytes expression: pre-bind types that can't be safely
                        // borrowed inline (ProgramId → Vec, scalars → fixed-size array).
                        // Note: [u8;32]/AccountId args are parsed as AccountId by
                        // idl_type_to_json_parse, so .as_ref() gives a valid &[u8].
                        match arg_ty.as_str() {
                            "[u8; 32]" | "[u8;32]" | "AccountId" | "account_id" => {
                                pda_seeds_code.push(format!("        {pname}.as_ref(),"));
                            }
                            "[u32; 8]" | "[u32;8]" | "ProgramId" => {
                                seed_parse_lines.push(format!("        let {pname}_seed_bytes: Vec<u8> = {pname}.iter().flat_map(|w| w.to_le_bytes()).collect();"));
                                pda_seeds_code.push(format!("        &{pname}_seed_bytes,"));
                            }
                            "u64" | "u32" | "u16" | "u8" | "i64" | "i32" | "i16" | "i8" | "u128" | "i128" => {
                                seed_parse_lines.push(format!("        let {pname}_seed_bytes = {pname}.to_le_bytes();"));
                                pda_seeds_code.push(format!("        &{pname}_seed_bytes,"));
                            }
                            "String" | "string" | "&str" => {
                                pda_seeds_code.push(format!("        {pname}.as_bytes(),"));
                            }
                            _ => pda_seeds_code.push(format!("        {pname}.as_ref(),")),
                        }
                    }
                    IdlSeed::Account { path } => {
                        let pname = rust_ident(path);
                        seed_parse_lines.push(format!(
                            "        let {pname} = parse_account_id(args[\"{path}\"].as_str().ok_or(\"missing {path}\")?)?;"
                        ));
                        pda_seeds_code.push(format!("        {pname}.as_ref(),"));
                    }
                }
            }

            writeln!(out).unwrap();
            writeln!(out, "/// FFI: fetch and decode `{acc_name}` PDA account.").unwrap();
            writeln!(out, "#[no_mangle]").unwrap();
            writeln!(out, "pub extern \"C\" fn {fn_name}(args_json: *const c_char) -> *mut c_char {{").unwrap();
            writeln!(out, "    ffi_call(move || {{").unwrap();
            writeln!(out, "        let args_str = match cstr_to_str(args_json) {{ Ok(s) => s.to_owned(), Err(e) => return Err(e) }};").unwrap();
            writeln!(out, "        {fn_name}_impl(&args_str)").unwrap();
            writeln!(out, "    }})").unwrap();
            writeln!(out, "}}").unwrap();
            writeln!(out).unwrap();
            writeln!(out, "fn {fn_name}_impl(args_str: &str) -> Result<String, String> {{").unwrap();
            writeln!(out, "    let args: serde_json::Value = serde_json::from_str(args_str).map_err(|e| format!(\"invalid JSON: {{e}}\"))?;").unwrap();
            writeln!(out, "    let program_id = parse_program_id_hex(args[\"program_id_hex\"].as_str().ok_or(\"missing program_id_hex\")?)?;").unwrap();
            writeln!(out, "    let wallet = init_wallet(&args)?;").unwrap();
            for line in &seed_parse_lines {
                writeln!(out, "{line}").unwrap();
            }
            writeln!(out, "    let pda = compute_pda_with_program(&program_id, &[").unwrap();
            for seed_line in &pda_seeds_code {
                writeln!(out, "{seed_line}").unwrap();
            }
            writeln!(out, "    ])?;").unwrap();
            writeln!(out, "    let rt = get_runtime();").unwrap();
            writeln!(out, "    let account = rt.block_on(async {{").unwrap();
            writeln!(out, "        wallet.sequencer_client.get_account(pda).await.map_err(|e| format!(\"get_account: {{e}}\"))").unwrap();
            writeln!(out, "    }})?;").unwrap();
            writeln!(out, "    let idl: spel_framework_core::idl::SpelIdl = serde_json::from_str(PROGRAM_IDL_JSON).map_err(|e| format!(\"IDL: {{e}}\"))?;").unwrap();
            writeln!(out, "    let state = match spel_framework_core::decode::decode_account_data_try_all(&account.data, &idl) {{").unwrap();
            writeln!(out, "        Some((_type_name, fields)) => fields,").unwrap();
            writeln!(out, "        None => serde_json::Value::Object(serde_json::Map::new()),").unwrap();
            writeln!(out, "    }};").unwrap();
            writeln!(out, "    Ok(serde_json::json!({{ \"success\": true, \"state\": state }}).to_string())").unwrap();
            writeln!(out, "}}").unwrap();
        }
    }
}

/// Generate a C header file from an IDL.
pub fn generate_header(idl: &SpelIdl) -> Result<String, String> {
    let mut out = String::new();
    let prefix = snake_case(&idl.name);
    let guard = format!("{}_FFI_H", prefix.to_uppercase());

    writeln!(out, "/* Auto-generated C header for {} FFI. DO NOT EDIT. */", idl.name).unwrap();
    writeln!(out, "#ifndef {guard}").unwrap();
    writeln!(out, "#define {guard}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#ifdef __cplusplus").unwrap();
    writeln!(out, "extern \"C\" {{").unwrap();
    writeln!(out, "#endif").unwrap();
    writeln!(out).unwrap();

    for ix in &idl.instructions {
        let fn_name = format!("{}_{}", prefix, snake_case(&ix.name));
        writeln!(out, "/* {} instruction */", ix.name).unwrap();
        writeln!(out, "char* {fn_name}(const char* args_json);").unwrap();
        writeln!(out).unwrap();
    }

    // Fetch function declarations — one per unique PDA account (by parameter name).
    // Mirrors generate_account_fetch_functions exactly.
    {
        let mut seen_fetch = std::collections::HashSet::new();
        for ix in &idl.instructions {
            for acc in &ix.accounts {
                if acc.pda.is_none() { continue; }
                let acc_name = snake_case(&acc.name);
                if !seen_fetch.insert(acc_name.clone()) { continue; }
                let fn_name = format!("{prefix}_fetch_{acc_name}");
                writeln!(out, "/* fetch {acc_name} account state */").unwrap();
                writeln!(out, "char* {fn_name}(const char* args_json);").unwrap();
                writeln!(out).unwrap();
            }
        }
    }

    writeln!(out, "/* wallet helpers */").unwrap();
    writeln!(out, "char* {prefix}_check_connection(const char* args_json);").unwrap();
    writeln!(out, "char* {prefix}_inspect_account(const char* args_json);").unwrap();
    writeln!(out, "char* {prefix}_list_accounts(const char* args_json);").unwrap();
    writeln!(out, "char* {prefix}_create_account(const char* args_json);").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "void {prefix}_free_string(char* s);").unwrap();
    writeln!(out, "char* {prefix}_version(void);").unwrap();
    writeln!(out, "char* {prefix}_program_id(void);").unwrap();
    writeln!(out, "char* {prefix}_decode_account(const char* args_json);").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#ifdef __cplusplus").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out, "#endif").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#endif /* {guard} */").unwrap();

    Ok(out)
}
