//! Auto-claim logic for `SpelOutput::execute()`.
//!
//! [`AutoClaim`] wraps `nssa_core::program::Claim` with a `None` variant for
//! accounts that don't need claiming. [`SpelOutput::execute`] turns
//! `(Account, AutoClaim)` pairs into the correct `AccountPostState` values.

use nssa_core::account::Account;
use nssa_core::program::{AccountPostState, ChainedCall, Claim, PdaSeed, ValidityWindow};
use nssa_core::NullifierPublicKey;

use crate::types::{IntoPostState, SpelOutput};

/// Describes the claim disposition for an account in a post-state.
///
/// Wraps `nssa_core::program::Claim` with an additional `None` variant for
/// accounts that are mutable or read-only (no ownership claim).
///
/// # Auto-claim rules (from `#[account(...)]` constraints)
///
/// | Constraint                          | AutoClaim variant          |
/// |-------------------------------------|----------------------------|
/// | `#[account(init, pda = ...)]`       | `AutoClaim::Claimed(Claim::Pda(seed))` |
/// | `#[account(init, signer)]`          | `AutoClaim::Claimed(Claim::Authorized)` |
/// | `#[account(init)]` (no pda/signer)  | `AutoClaim::Claimed(Claim::Authorized)` |
/// | `#[account(mut)]`                   | `AutoClaim::None`          |
/// | `#[account]` (read-only)            | `AutoClaim::None`          |
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AutoClaim {
    /// The account should be claimed with the given [`Claim`] type.
    Claimed(Claim),
    /// The account is mutable or read-only — no claim is requested.
    None,
}

impl AutoClaim {
    /// Returns `true` if this will result in `AccountPostState::new_claimed`.
    #[must_use]
    pub fn is_claimed(&self) -> bool {
        matches!(self, AutoClaim::Claimed(_))
    }

    /// Convert an account and this auto-claim into an `AccountPostState`.
    #[must_use]
    pub fn to_post_state(&self, account: Account) -> AccountPostState {
        match self {
            AutoClaim::Claimed(claim) => AccountPostState::new_claimed(account, *claim),
            AutoClaim::None => AccountPostState::new(account),
        }
    }

    /// Create an `AutoClaim` for a PDA-initialized account from raw seed bytes.
    ///
    /// The seed bytes are zero-padded to 32 bytes and wrapped in a `PdaSeed`.
    pub fn pda_from_seeds(seeds: &[&[u8]]) -> Self {
        // Combine seeds into a single PdaSeed using the same logic as compute_pda
        let combined = if seeds.len() == 1 {
            // Single seed: use raw 32 bytes (no padding), consistent with compute_pda
            assert!(
                seeds[0].len() == 32,
                "pda_from_seeds: single seed must be 32 bytes"
            );
            let mut buf = [0u8; 32];
            buf.copy_from_slice(seeds[0]);
            buf
        } else {
            use sha2::{Digest, Sha256};
            let mut hasher = Sha256::new();
            for seed in seeds {
                hasher.update(seed);
            }
            hasher.finalize().into()
        };
        AutoClaim::Claimed(Claim::Pda(PdaSeed::new(combined)))
    }

    /// Create an `AutoClaim` for a private PDA-initialized account from raw seed bytes.
    ///
    /// Identical to [`pda_from_seeds`] in terms of the emitted claim — the circuit
    /// reuses `Claim::Pda(seed)` for private PDAs and derives the address via
    /// `AccountId::for_private_pda` using the `npk` it receives separately through
    /// `PrivacyPreservingCircuitInput.private_account_keys`.
    ///
    /// The `npk` parameter is accepted for documentation clarity; it is not encoded
    /// into the claim itself.
    pub fn private_pda_from_seeds(seeds: &[&[u8]], _npk: &NullifierPublicKey) -> Self {
        Self::pda_from_seeds(seeds)
    }
}

// ── IntoPostState implementations ───────────────────────────────────────

impl IntoPostState for (Account, AutoClaim) {
    fn into_post_state(self) -> AccountPostState {
        self.1.to_post_state(self.0)
    }
}

impl IntoPostState for (Account, &AutoClaim) {
    fn into_post_state(self) -> AccountPostState {
        self.1.to_post_state(self.0)
    }
}

impl IntoPostState for AccountPostState {
    fn into_post_state(self) -> AccountPostState {
        self
    }
}

impl IntoPostState for Account {
    fn into_post_state(self) -> AccountPostState {
        AccountPostState::new(self)
    }
}

// ── SpelOutput::execute ─────────────────────────────────────────────────

impl SpelOutput {
    /// Build a `SpelOutput` from accounts paired with auto-claim metadata.
    ///
    /// Each item is converted to an `AccountPostState` via [`IntoPostState`].
    /// Accepts `Vec<(Account, AutoClaim)>`, `Vec<AccountPostState>`, or any
    /// iterator of `impl IntoPostState`.
    ///
    /// # Examples
    ///
    /// ```rust,ignore
    /// // Inside a handler generated by #[lez_program]:
    /// Ok(SpelOutput::execute(
    ///     vec![
    ///         (state.account.clone(), AutoClaim::Claimed(Claim::Authorized)),
    ///         (authority.account.clone(), AutoClaim::None),
    ///     ],
    ///     vec![],  // chained calls
    /// ))
    /// ```
    pub fn execute(
        accounts: impl IntoIterator<Item = impl IntoPostState>,
        calls: Vec<ChainedCall>,
    ) -> Self {
        let post_states = accounts
            .into_iter()
            .map(IntoPostState::into_post_state)
            .collect();
        Self {
            post_states,
            chained_calls: calls,
            block_validity_window: ValidityWindow::new_unbounded(),
            timestamp_validity_window: ValidityWindow::new_unbounded(),
        }
    }

    /// Build a `SpelOutput` by zipping a list of accounts with a matching
    /// list of auto-claims.
    ///
    /// This is the primary method used by macro-generated `__claims_*()` helpers.
    ///
    /// # Panics
    ///
    /// Panics if `accounts` and `claims` have different lengths.
    pub fn execute_with_claims(
        accounts: &[Account],
        claims: &[AutoClaim],
        calls: Vec<ChainedCall>,
    ) -> Self {
        assert_eq!(
            accounts.len(),
            claims.len(),
            "execute_with_claims: accounts.len() ({}) != claims.len() ({})",
            accounts.len(),
            claims.len(),
        );
        let post_states = accounts
            .iter()
            .zip(claims.iter())
            .map(|(acc, claim)| claim.to_post_state(acc.clone()))
            .collect();
        Self {
            post_states,
            chained_calls: calls,
            block_validity_window: ValidityWindow::new_unbounded(),
            timestamp_validity_window: ValidityWindow::new_unbounded(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn auto_claim_is_claimed() {
        assert!(AutoClaim::Claimed(Claim::Authorized).is_claimed());
        assert!(AutoClaim::Claimed(Claim::Pda(PdaSeed::new([0; 32]))).is_claimed());
        assert!(!AutoClaim::None.is_claimed());
    }

    /// Convenience helper: returns a `SpelOutput` with no accounts or calls.
    /// Reduces boilerplate in validity-window tests below.
    fn empty_output() -> SpelOutput {
        SpelOutput::execute(Vec::<(Account, AutoClaim)>::new(), vec![])
    }

    #[test]
    fn execute_auto_claims() {
        let account_a = Account::default();
        let account_b = Account::default();

        let output = SpelOutput::execute(
            vec![
                (account_a.clone(), AutoClaim::Claimed(Claim::Authorized)),
                (account_b.clone(), AutoClaim::None),
            ],
            vec![],
        );

        assert_eq!(output.post_states.len(), 2);
        assert!(output.post_states[0].required_claim().is_some());
        assert!(output.post_states[1].required_claim().is_none());
        assert!(output.chained_calls.is_empty());
    }

    #[test]
    fn execute_with_claims_zips_correctly() {
        let accounts = vec![Account::default(), Account::default(), Account::default()];
        let claims = vec![
            AutoClaim::Claimed(Claim::Pda(PdaSeed::new([0; 32]))),
            AutoClaim::Claimed(Claim::Authorized),
            AutoClaim::None,
        ];

        let output = SpelOutput::execute_with_claims(&accounts, &claims, vec![]);

        assert_eq!(output.post_states.len(), 3);
        assert!(output.post_states[0].required_claim().is_some());
        assert!(output.post_states[1].required_claim().is_some());
        assert!(output.post_states[2].required_claim().is_none());
    }

    #[test]
    fn execute_empty() {
        let output = SpelOutput::execute(Vec::<(Account, AutoClaim)>::new(), vec![]);
        assert!(output.post_states.is_empty());
        assert!(output.chained_calls.is_empty());
    }

    #[test]
    #[should_panic(expected = "accounts.len()")]
    fn execute_with_claims_panics_on_mismatch() {
        SpelOutput::execute_with_claims(
            &[Account::default()],
            &[AutoClaim::None, AutoClaim::None],
            vec![],
        );
    }

    #[test]
    fn execute_accepts_raw_post_states() {
        let ps = AccountPostState::new(Account::default());
        let output = SpelOutput::execute(vec![ps], vec![]);
        assert_eq!(output.post_states.len(), 1);
        assert!(output.post_states[0].required_claim().is_none());
    }

    #[test]
    fn pda_from_seeds_single() {
        let claim = AutoClaim::pda_from_seeds(&[&[0u8; 32]]);
        assert!(claim.is_claimed());
    }

    #[test]
    fn pda_from_seeds_multi() {
        let claim = AutoClaim::pda_from_seeds(&[&[1u8; 32], &[2u8; 32]]);
        assert!(claim.is_claimed());
    }

    // ── Validity window tests ────────────────────────────────────────────

    /// Existing programs that don't call any validity window builder get unbounded
    /// windows, which matches the prior hard-coded behavior.
    #[test]
    fn default_output_has_unbounded_windows() {
        let output = empty_output();
        assert_eq!(output.block_validity_window.start(), None);
        assert_eq!(output.block_validity_window.end(), None);
        assert_eq!(output.timestamp_validity_window.start(), None);
        assert_eq!(output.timestamp_validity_window.end(), None);
    }

    #[test]
    fn execute_with_claims_default_windows_unbounded() {
        let output = SpelOutput::execute_with_claims(&[], &[], vec![]);
        assert_eq!(output.block_validity_window.start(), None);
        assert_eq!(output.block_validity_window.end(), None);
    }

    #[test]
    fn with_block_validity_window_range_from() {
        let output = empty_output().with_block_validity_window(42u64..);
        assert_eq!(output.block_validity_window.start(), Some(42));
        assert_eq!(output.block_validity_window.end(), None);
    }

    #[test]
    fn with_block_validity_window_range_to() {
        let output = empty_output().with_block_validity_window(..100u64);
        assert_eq!(output.block_validity_window.start(), None);
        assert_eq!(output.block_validity_window.end(), Some(100));
    }

    #[test]
    fn with_block_validity_window_unbounded() {
        let output = empty_output().with_block_validity_window(..);
        assert_eq!(output.block_validity_window.start(), None);
        assert_eq!(output.block_validity_window.end(), None);
    }

    #[test]
    fn try_with_block_validity_window_valid_range() {
        let output = empty_output()
            .try_with_block_validity_window(10u64..20)
            .expect("10..20 is a valid range");
        assert_eq!(output.block_validity_window.start(), Some(10));
        assert_eq!(output.block_validity_window.end(), Some(20));
    }

    #[test]
    fn try_with_block_validity_window_empty_range_errors() {
        let result = empty_output().try_with_block_validity_window(5u64..5);
        assert!(result.is_err(), "empty range should return Err");
    }

    #[test]
    #[allow(clippy::reversed_empty_ranges)]
    fn try_with_block_validity_window_inverted_range_errors() {
        let result = empty_output().try_with_block_validity_window(10u64..5);
        assert!(result.is_err(), "inverted range should return Err");
    }

    /// RangeFull (`..`) is an infallible conversion — use the infallible
    /// `with_block_validity_window` variant, not `try_with_*`.
    #[test]
    fn with_block_validity_window_range_full_succeeds() {
        let output = empty_output().with_block_validity_window(..);
        assert_eq!(output.block_validity_window.start(), None);
        assert_eq!(output.block_validity_window.end(), None);
    }

    /// RangeFull (`..`) is an infallible conversion — use the infallible
    /// `with_timestamp_validity_window` variant, not `try_with_*`.
    #[test]
    fn with_timestamp_validity_window_range_full_succeeds() {
        let output = empty_output().with_timestamp_validity_window(..);
        assert_eq!(output.timestamp_validity_window.start(), None);
        assert_eq!(output.timestamp_validity_window.end(), None);
    }

    #[test]
    fn with_timestamp_validity_window_range_from() {
        let output = empty_output().with_timestamp_validity_window(1_700_000_000u64..);
        assert_eq!(
            output.timestamp_validity_window.start(),
            Some(1_700_000_000)
        );
        assert_eq!(output.timestamp_validity_window.end(), None);
    }

    #[test]
    fn try_with_timestamp_validity_window_valid_range() {
        let output = empty_output()
            .try_with_timestamp_validity_window(1_000u64..2_000)
            .expect("1000..2000 is a valid range");
        assert_eq!(output.timestamp_validity_window.start(), Some(1_000));
        assert_eq!(output.timestamp_validity_window.end(), Some(2_000));
    }

    #[test]
    fn try_with_timestamp_validity_window_empty_range_errors() {
        let result = empty_output().try_with_timestamp_validity_window(99u64..99);
        assert!(result.is_err());
    }

    #[test]
    #[allow(clippy::reversed_empty_ranges)]
    fn try_with_timestamp_validity_window_inverted_range_errors() {
        let result = empty_output().try_with_timestamp_validity_window(2_000u64..1_000);
        assert!(result.is_err(), "inverted range should return Err");
    }

    #[test]
    fn into_parts_returns_all_fields() {
        let output = SpelOutput::execute(Vec::<(Account, AutoClaim)>::new(), vec![])
            .with_block_validity_window(5u64..)
            .try_with_timestamp_validity_window(100u64..200)
            .unwrap();

        let parts = output.into_parts();
        let post_states = parts.post_states;
        let chained_calls = parts.chained_calls;
        let block_window = parts.block_validity_window;
        let ts_window = parts.timestamp_validity_window;
        assert!(post_states.is_empty());
        assert!(chained_calls.is_empty());
        assert_eq!(block_window.start(), Some(5));
        assert_eq!(block_window.end(), None);
        assert_eq!(ts_window.start(), Some(100));
        assert_eq!(ts_window.end(), Some(200));
    }
}
