//! State-diff plumbing for `SpelOutput::execute()`.
//!
//! [`IntoStateDiff`] turns what a handler returns into the
//! `nssa_core::program::AccountStateDiff` values LEZ expects.
//!
//! # Where the claims went
//!
//! Up to LEZ v0.2.4 a program declared ownership explicitly, via
//! `Claim::Authorized` / `Claim::Pda(seed)` attached to each post-state, and this
//! module wrapped that in an `AutoClaim` enum driven by the `#[account(...)]`
//! constraints. v0.2.5 removed `Claim` entirely: writing data to a default-owned
//! account *is* the claim, applied by `acquire_ownership_on_data_write` during
//! validation. So `#[account(init)]`, `#[account(init, signer)]` and
//! `#[account(init, pda = ...)]` have nothing left to emit here.
//!
//! The PDA *address* guarantee is unaffected — it never came from the claim. The
//! generated per-instruction validation still checks each `pda`-constrained
//! account against [`crate::pda::compute_pda`], which is what actually proves the
//! account sits at the derived address.

use nssa_core::account::AccountWithMetadata;
use nssa_core::program::{AccountStateDiff, ChainedCall, ValidityWindow};

use crate::types::{IntoStateDiff, SpelOutput};

// ── IntoStateDiff implementations ───────────────────────────────────────

impl IntoStateDiff for AccountStateDiff {
    fn into_state_diff(self) -> AccountStateDiff {
        self
    }
}

impl IntoStateDiff for AccountWithMetadata {
    /// An account handed back untouched: no balance delta, no data change.
    fn into_state_diff(self) -> AccountStateDiff {
        AccountStateDiff::unchanged(self)
    }
}

// ── SpelOutput::execute ─────────────────────────────────────────────────

impl SpelOutput {
    /// Build a `SpelOutput` from per-account state diffs.
    ///
    /// Each item is converted via [`IntoStateDiff`], so this accepts
    /// `Vec<AccountStateDiff>` or `Vec<AccountWithMetadata>` (the latter meaning
    /// "returned unchanged"), or any iterator mixing the two.
    ///
    /// Every account the transaction declared must appear in the output — LEZ
    /// v0.2.5 rejects a diff that omits one with
    /// `DeclaredAccountMissingFromOutput`. Return read-only accounts as
    /// `AccountStateDiff::unchanged`, never by dropping them.
    ///
    /// # Examples
    ///
    /// ```rust,ignore
    /// // Inside a handler generated by #[lez_program]:
    /// Ok(SpelOutput::execute(
    ///     vec![
    ///         AccountStateDiff::new(state, BalanceDiff::Add(0), new_data),
    ///         AccountStateDiff::unchanged(authority),
    ///     ],
    ///     vec![],  // chained calls
    /// ))
    /// ```
    pub fn execute(
        diffs: impl IntoIterator<Item = impl IntoStateDiff>,
        calls: Vec<ChainedCall>,
    ) -> Self {
        let state_diffs = diffs
            .into_iter()
            .map(IntoStateDiff::into_state_diff)
            .collect();
        Self {
            state_diffs,
            chained_calls: calls,
            block_validity_window: ValidityWindow::new_unbounded(),
            timestamp_validity_window: ValidityWindow::new_unbounded(),
        }
    }
}

#[cfg(test)]
mod tests {
    use nssa_core::account::{Account, AccountId, BalanceDiff, Data};

    use super::*;

    fn account(id: u8) -> AccountWithMetadata {
        AccountWithMetadata {
            account: Account::default(),
            account_id: AccountId::new([id; 32]),
            is_authorized: false,
        }
    }

    /// A chained call to `program`, naming one pre-state by id.
    ///
    /// Mirrors how a real caller delegates: the account is returned unchanged in
    /// the caller's own diffs while the mutation is handed to the callee, which
    /// executes as that program and so may act on accounts it owns.
    fn call_to(program: u8) -> ChainedCall {
        ChainedCall {
            program_account_id: AccountId::new([program; 32]),
            instruction_data: vec![],
            pre_state_ids: vec![AccountId::new([program; 32])],
            pda_seeds: vec![],
        }
    }

    #[test]
    fn execute_carries_chained_calls() {
        let output = SpelOutput::execute(vec![account(1)], vec![call_to(7)]);
        assert_eq!(output.state_diffs.len(), 1);
        assert_eq!(
            output.chained_calls.len(),
            1,
            "the call must reach the output"
        );
        assert_eq!(
            output.chained_calls[0].program_account_id,
            AccountId::new([7; 32])
        );
    }

    #[test]
    fn bare_account_becomes_an_unchanged_diff() {
        let output = SpelOutput::execute(vec![account(1)], vec![]);
        let diff = &output.state_diffs[0];
        assert_eq!(
            diff.post_data, None,
            "an untouched account must report no data change"
        );
        assert_eq!(diff.post_balance_diff, BalanceDiff::Add(0));
    }

    #[test]
    fn explicit_diffs_pass_through_unchanged() {
        let pre = account(2);
        let data = Data::try_from(vec![1, 2, 3]).expect("fits under DATA_MAX_LENGTH");
        let output = SpelOutput::execute(
            vec![AccountStateDiff::new(
                pre.clone(),
                BalanceDiff::Sub(5),
                data.clone(),
            )],
            vec![],
        );
        let diff = &output.state_diffs[0];
        assert_eq!(diff.pre_state.account_id, pre.account_id);
        assert_eq!(diff.post_balance_diff, BalanceDiff::Sub(5));
        assert_eq!(
            diff.post_data.as_ref(),
            Some(&data),
            "data differing from the pre-state must survive as a change"
        );
    }

    #[test]
    fn execute_accepts_an_empty_output() {
        let output = SpelOutput::execute(Vec::<AccountStateDiff>::new(), vec![]);
        assert!(output.state_diffs.is_empty());
        assert!(output.chained_calls.is_empty());
    }
}
