//! Typed Rust client generation from LEZ IDL.

use lez_framework_core::idl::*;
use std::fmt::Write;
use crate::util::*;

/// Generate a typed Rust client module from an IDL.
pub fn generate_client(idl: &LezIdl) -> Result<String, String> {
    let mut out = String::new();
    let program_pascal = pascal_case(&idl.name);

    // Header
    writeln!(out, "//! Auto-generated client for the {} program.", idl.name).unwrap();
    writeln!(out, "//! Generated by lez-client-gen from IDL v{}.", idl.version).unwrap();
    writeln!(out, "//! DO NOT EDIT — regenerate from IDL instead.").unwrap();
    writeln!(out).unwrap();

    // Imports
    writeln!(out, "use nssa::{{").unwrap();
    writeln!(out, "    AccountId, ProgramId, PublicTransaction,").unwrap();
    writeln!(out, "    public_transaction::{{Message, WitnessSet}},").unwrap();
    writeln!(out, "}};").unwrap();
    writeln!(out, "use serde::{{Deserialize, Serialize}};").unwrap();
    writeln!(out, "use wallet::WalletCore;").unwrap();
    writeln!(out).unwrap();

    // PDA helper — SHA-256(seed1 || seed2 || ...) matching on-chain derivation
    writeln!(out, "/// Compute a PDA by SHA-256 hashing concatenated seeds.").unwrap();
    writeln!(out, "/// Matches the on-chain nssa PDA derivation (not XOR).").unwrap();
    writeln!(out, "fn compute_pda(seeds: &[&[u8]]) -> AccountId {{").unwrap();
    writeln!(out, "    use sha2::{{Sha256, Digest}};").unwrap();
    writeln!(out, "    let mut hasher = Sha256::new();").unwrap();
    writeln!(out, "    for seed in seeds {{").unwrap();
    writeln!(out, "        let mut padded = [0u8; 32];").unwrap();
    writeln!(out, "        let len = seed.len().min(32);").unwrap();
    writeln!(out, "        padded[..len].copy_from_slice(&seed[..len]);").unwrap();
    writeln!(out, "        hasher.update(&padded);").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    let hash: [u8; 32] = hasher.finalize().into();").unwrap();
    writeln!(out, "    AccountId::from(hash)").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Parse helpers
    writeln!(out, "/// Parse a hex string into ProgramId [u32; 8] (little-endian byte order).").unwrap();
    writeln!(out, "pub fn parse_program_id_hex(s: &str) -> Result<ProgramId, String> {{").unwrap();
    writeln!(out, "    let s = s.trim_start_matches(\"0x\");").unwrap();
    writeln!(out, "    if s.len() != 64 {{").unwrap();
    writeln!(out, "        return Err(format!(\"program_id hex must be 64 chars, got {{}}\", s.len()));").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    let bytes = hex::decode(s).map_err(|e| format!(\"invalid hex: {{}}\", e))?;").unwrap();
    writeln!(out, "    let mut pid = [0u32; 8];").unwrap();
    writeln!(out, "    for (i, chunk) in bytes.chunks(4).enumerate() {{").unwrap();
    writeln!(out, "        pid[i] = u32::from_le_bytes(chunk.try_into().unwrap());").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    Ok(pid)").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Instruction enum
    writeln!(out, "#[derive(Clone, Debug, Serialize, Deserialize)]").unwrap();
    writeln!(out, "pub enum {}Instruction {{", program_pascal).unwrap();
    for ix in &idl.instructions {
        let variant = pascal_case(&ix.name);
        if ix.args.is_empty() {
            writeln!(out, "    {},", variant).unwrap();
        } else {
            writeln!(out, "    {} {{", variant).unwrap();
            for arg in &ix.args {
                writeln!(out, "        {}: {},", rust_ident(&arg.name), idl_type_to_rust(&arg.type_)).unwrap();
            }
            writeln!(out, "    }},").unwrap();
        }
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Per-instruction account structs
    for ix in &idl.instructions {
        let accounts_name = format!("{}Accounts", pascal_case(&ix.name));
        writeln!(out, "pub struct {} {{", accounts_name).unwrap();
        for acc in &ix.accounts {
            if acc.rest {
                writeln!(out, "    pub {}: Vec<AccountId>,", rust_ident(&acc.name)).unwrap();
            } else {
                writeln!(out, "    pub {}: AccountId,", rust_ident(&acc.name)).unwrap();
            }
        }
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    // Client struct
    writeln!(out, "pub struct {}Client<'w> {{", program_pascal).unwrap();
    writeln!(out, "    pub wallet: &'w WalletCore,").unwrap();
    writeln!(out, "    pub program_id: ProgramId,").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "impl<'w> {}Client<'w> {{", program_pascal).unwrap();
    writeln!(out, "    pub fn new(wallet: &'w WalletCore, program_id: ProgramId) -> Self {{").unwrap();
    writeln!(out, "        Self {{ wallet, program_id }}").unwrap();
    writeln!(out, "    }}").unwrap();

    for ix in &idl.instructions {
        let method = rust_ident(&ix.name);
        let accounts_name = format!("{}Accounts", pascal_case(&ix.name));
        let variant = pascal_case(&ix.name);

        writeln!(out).unwrap();
        write!(out, "    pub async fn {}(\n        &self,\n        accounts: {}", method, accounts_name).unwrap();
        for arg in &ix.args {
            write!(out, ",\n        {}: {}", rust_ident(&arg.name), idl_type_to_rust(&arg.type_)).unwrap();
        }
        writeln!(out, ",\n    ) -> Result<String, String> {{").unwrap();

        // Build instruction
        if ix.args.is_empty() {
            writeln!(out, "        let instruction = {}Instruction::{};", program_pascal, variant).unwrap();
        } else {
            writeln!(out, "        let instruction = {}Instruction::{} {{", program_pascal, variant).unwrap();
            for arg in &ix.args {
                writeln!(out, "            {},", rust_ident(&arg.name)).unwrap();
            }
            writeln!(out, "        }};").unwrap();
        }

        // Account IDs
        writeln!(out, "        let mut account_ids: Vec<AccountId> = vec![").unwrap();
        for acc in ix.accounts.iter().filter(|a| !a.rest) {
            writeln!(out, "            accounts.{},", rust_ident(&acc.name)).unwrap();
        }
        writeln!(out, "        ];").unwrap();
        for acc in ix.accounts.iter().filter(|a| a.rest) {
            writeln!(out, "        account_ids.extend_from_slice(&accounts.{});", rust_ident(&acc.name)).unwrap();
        }

        // Signers
        let signers: Vec<_> = ix.accounts.iter().filter(|a| a.signer).collect();
        writeln!(out, "        let signer_ids: Vec<AccountId> = vec![").unwrap();
        for s in &signers {
            writeln!(out, "            accounts.{},", rust_ident(&s.name)).unwrap();
        }
        writeln!(out, "        ];").unwrap();
        writeln!(out, "        let nonces = self.wallet.get_accounts_nonces(signer_ids.clone()).await").unwrap();
        writeln!(out, "            .map_err(|e| format!(\"nonces: {{}}\", e))?;").unwrap();
        writeln!(out, "        let mut signing_keys = Vec::new();").unwrap();
        writeln!(out, "        for sid in &signer_ids {{").unwrap();
        writeln!(out, "            let key = self.wallet.storage().user_data").unwrap();
        writeln!(out, "                .get_pub_account_signing_key(*sid)").unwrap();
        writeln!(out, "                .ok_or_else(|| format!(\"signing key not found for {{}}\", sid))?;").unwrap();
        writeln!(out, "            signing_keys.push(key);").unwrap();
        writeln!(out, "        }}").unwrap();
        writeln!(out, "        let message = Message::try_new(self.program_id, account_ids, nonces, instruction)").unwrap();
        writeln!(out, "            .map_err(|e| format!(\"message: {{:?}}\", e))?;").unwrap();
        writeln!(out, "        let witness_set = WitnessSet::for_message(&message, &signing_keys);").unwrap();
        writeln!(out, "        let tx = PublicTransaction::new(message, witness_set);").unwrap();
        writeln!(out, "        let response = self.wallet.sequencer_client.send_tx_public(tx).await").unwrap();
        writeln!(out, "            .map_err(|e| format!(\"submit: {{}}\", e))?;").unwrap();
        writeln!(out, "        Ok(response.tx_hash.to_string())").unwrap();
        writeln!(out, "    }}").unwrap();
    }

    // PDA helpers
    for ix in &idl.instructions {
        for acc in &ix.accounts {
            if let Some(pda) = &acc.pda {
                writeln!(out).unwrap();
                let method_name = format!("compute_{}_pda", snake_case(&acc.name));
                let mut pda_args: Vec<(String, String)> = Vec::new();
                for seed in &pda.seeds {
                    match seed {
                        IdlSeed::Account { path } => pda_args.push((snake_case(path), "AccountId".to_string())),
                        IdlSeed::Arg { path } => {
                            let ty = ix.args.iter().find(|a| a.name == *path)
                                .map(|a| idl_type_to_rust(&a.type_))
                                .unwrap_or_else(|| "String".to_string());
                            pda_args.push((snake_case(path), ty));
                        }
                        IdlSeed::Const { .. } => {}
                    }
                }
                write!(out, "    pub fn {}(", method_name).unwrap();
                for (i, (name, ty)) in pda_args.iter().enumerate() {
                    if i > 0 { write!(out, ", ").unwrap(); }
                    write!(out, "{}: &{}", name, ty).unwrap();
                }
                writeln!(out, ") -> AccountId {{").unwrap();
                writeln!(out, "        compute_pda(&[").unwrap();
                for seed in &pda.seeds {
                    match seed {
                        IdlSeed::Const { value } => writeln!(out, "            b\"{}\",", value).unwrap(),
                        IdlSeed::Account { path } => writeln!(out, "            {}.as_ref(),", snake_case(path)).unwrap(),
                        IdlSeed::Arg { path } => writeln!(out, "            {}.to_string().as_bytes(),", snake_case(path)).unwrap(),
                    }
                }
                writeln!(out, "        ])").unwrap();
                writeln!(out, "    }}").unwrap();
            }
        }
    }

    writeln!(out, "}}").unwrap();
    Ok(out)
}
