//! C FFI wrapper generation from LEZ IDL.
//!
//! Generates `extern "C"` functions that accept JSON strings and return JSON strings,
//! matching the pattern used in lez-multisig-ffi.

use lez_framework_core::idl::*;
use std::fmt::Write;
use crate::util::*;

/// Generate C FFI wrapper source code from an IDL.
pub fn generate_ffi(idl: &LezIdl) -> Result<String, String> {
    let mut out = String::new();
    let prefix = snake_case(&idl.name);

    // Header
    writeln!(out, "//! Auto-generated C FFI for the {} program.", idl.name).unwrap();
    writeln!(out, "//! Generated by lez-client-gen. DO NOT EDIT.").unwrap();
    writeln!(out).unwrap();

    // Imports
    writeln!(out, "use std::ffi::{{CStr, CString}};").unwrap();
    writeln!(out, "use std::os::raw::c_char;").unwrap();
    writeln!(out, "use serde_json::{{Value, json}};").unwrap();
    writeln!(out).unwrap();

    // Helpers
    writeln!(out, "fn cstr_to_str<'a>(ptr: *const c_char) -> Result<&'a str, String> {{").unwrap();
    writeln!(out, "    if ptr.is_null() {{ return Err(\"null pointer\".into()); }}").unwrap();
    writeln!(out, "    unsafe {{ CStr::from_ptr(ptr) }}.to_str().map_err(|e| format!(\"invalid UTF-8: {{}}\", e))").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "fn to_cstring(s: String) -> *mut c_char {{").unwrap();
    writeln!(out, "    CString::new(s).unwrap_or_else(|_|").unwrap();
    writeln!(out, "        CString::new(r#\"{{\"success\":false,\"error\":\"null byte\"}}\"#).unwrap()").unwrap();
    writeln!(out, "    ).into_raw()").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "fn error_json(msg: &str) -> *mut c_char {{").unwrap();
    out.push_str("    to_cstring(format!(r#\"{{\"success\":false,\"error\":{}}}\"#, serde_json::json!(msg)))\n");
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Type parsing helpers
    writeln!(out, "/// Parse AccountId from base58 or hex string.").unwrap();
    writeln!(out, "fn parse_account_id(s: &str) -> Result<nssa::AccountId, String> {{").unwrap();
    writeln!(out, "    // Try base58 first (native format)").unwrap();
    writeln!(out, "    if let Ok(id) = s.parse() {{ return Ok(id); }}").unwrap();
    writeln!(out, "    // Fall back to hex").unwrap();
    writeln!(out, "    let s = s.trim_start_matches(\"0x\");").unwrap();
    writeln!(out, "    if s.len() == 64 {{").unwrap();
    writeln!(out, "        let bytes = hex::decode(s).map_err(|e| format!(\"invalid hex: {{}}\", e))?;").unwrap();
    writeln!(out, "        let mut arr = [0u8; 32];").unwrap();
    writeln!(out, "        arr.copy_from_slice(&bytes);").unwrap();
    writeln!(out, "        return Ok(nssa::AccountId::from(arr));").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    Err(format!(\"invalid AccountId: {{}}\", s))").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "/// Parse ProgramId from hex string (little-endian [u32; 8]).").unwrap();
    writeln!(out, "fn parse_program_id(s: &str) -> Result<nssa::ProgramId, String> {{").unwrap();
    writeln!(out, "    let s = s.trim_start_matches(\"0x\");").unwrap();
    writeln!(out, "    if s.len() != 64 {{").unwrap();
    writeln!(out, "        return Err(format!(\"program_id hex must be 64 chars, got {{}}\", s.len()));").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    let bytes = hex::decode(s).map_err(|e| format!(\"invalid hex: {{}}\", e))?;").unwrap();
    writeln!(out, "    let mut pid = [0u32; 8];").unwrap();
    writeln!(out, "    for (i, chunk) in bytes.chunks(4).enumerate() {{").unwrap();
    writeln!(out, "        pid[i] = u32::from_le_bytes(chunk.try_into().unwrap());").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    Ok(pid)").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // PDA computation — SHA-256(seed1 || seed2 || ...) matching on-chain derivation
    writeln!(out, "fn compute_pda(seeds: &[&[u8]]) -> nssa::AccountId {{").unwrap();
    writeln!(out, "    use sha2::{{Sha256, Digest}};").unwrap();
    writeln!(out, "    let mut hasher = Sha256::new();").unwrap();
    writeln!(out, "    for seed in seeds {{").unwrap();
    writeln!(out, "        let mut padded = [0u8; 32];").unwrap();
    writeln!(out, "        let len = seed.len().min(32);").unwrap();
    writeln!(out, "        padded[..len].copy_from_slice(&seed[..len]);").unwrap();
    writeln!(out, "        hasher.update(&padded);").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    let hash: [u8; 32] = hasher.finalize().into();").unwrap();
    writeln!(out, "    nssa::AccountId::from(hash)").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Per-instruction FFI functions
    for ix in &idl.instructions {
        let fn_name = format!("{}_{}", prefix, snake_case(&ix.name));

        writeln!(out, "/// FFI: {} instruction.", ix.name).unwrap();
        writeln!(out, "/// Args JSON: see IDL for field names and types.").unwrap();
        writeln!(out, "#[no_mangle]").unwrap();
        writeln!(out, "pub extern \"C\" fn {fn_name}(args_json: *const c_char) -> *mut c_char {{").unwrap();
        writeln!(out, "    let args = match cstr_to_str(args_json) {{").unwrap();
        writeln!(out, "        Ok(s) => s,").unwrap();
        writeln!(out, "        Err(e) => return error_json(&e),").unwrap();
        writeln!(out, "    }};").unwrap();
        writeln!(out, "    match {fn_name}_impl(args) {{").unwrap();
        writeln!(out, "        Ok(result) => to_cstring(result),").unwrap();
        writeln!(out, "        Err(e) => error_json(&e),").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        // Implementation function
        writeln!(out, "fn {fn_name}_impl(args: &str) -> Result<String, String> {{").unwrap();
        writeln!(out, "    let v: Value = serde_json::from_str(args).map_err(|e| format!(\"invalid JSON: {{}}\", e))?;").unwrap();
        writeln!(out).unwrap();

        // Parse instruction args
        for arg in &ix.args {
            let name = rust_ident(&arg.name);
            let parse_expr = idl_type_to_json_parse(&arg.type_, &format!("v[\"{}\"]", arg.name));
            writeln!(out, "    let {name} = {parse_expr};").unwrap();
        }

        // Parse/compute account IDs
        writeln!(out).unwrap();
        writeln!(out, "    // Build account list in correct IDL order").unwrap();
        for acc in &ix.accounts {
            let name = rust_ident(&acc.name);
            if let Some(pda) = &acc.pda {
                // Generate PDA computation inline
                writeln!(out, "    let {name} = compute_pda(&[").unwrap();
                for seed in &pda.seeds {
                    match seed {
                        IdlSeed::Const { value } => {
                            writeln!(out, "        b\"{value}\",").unwrap();
                        }
                        IdlSeed::Account { path } => {
                            writeln!(out, "        {}.as_ref(),", rust_ident(path)).unwrap();
                        }
                        IdlSeed::Arg { path } => {
                            // For ProgramId args, convert to bytes
                            if let Some(arg) = ix.args.iter().find(|a| a.name == *path) {
                                match &arg.type_ {
                                    IdlType::Primitive(p) if p == "[u32; 8]" || p == "[u32;8]" || p == "ProgramId" => {
                                        writeln!(out, "        &{}.iter().flat_map(|w| w.to_le_bytes()).collect::<Vec<u8>>(),",
                                            rust_ident(path)).unwrap();
                                    }
                                    _ => {
                                        writeln!(out, "        {}.to_string().as_bytes(),", rust_ident(path)).unwrap();
                                    }
                                }
                            } else {
                                writeln!(out, "        {}.to_string().as_bytes(),", rust_ident(path)).unwrap();
                            }
                        }
                    }
                }
                writeln!(out, "    ]);").unwrap();
            } else if acc.rest {
                let parse_expr = idl_type_to_json_parse(
                    &IdlType::Vec { vec: Box::new(IdlType::Primitive("AccountId".to_string())) },
                    &format!("v[\"{}\"]", acc.name),
                );
                writeln!(out, "    let {name} = {parse_expr};").unwrap();
            } else if acc.signer {
                writeln!(out, "    let {name} = parse_account_id(v[\"{}\"].as_str().ok_or(\"missing {}\")?)?;",
                    acc.name, acc.name).unwrap();
            } else {
                writeln!(out, "    let {name} = parse_account_id(v[\"{}\"].as_str().ok_or(\"missing {}\")?)?;",
                    acc.name, acc.name).unwrap();
            }
        }

        // Build account_ids vec
        writeln!(out).unwrap();
        writeln!(out, "    let mut account_ids = vec![").unwrap();
        for acc in ix.accounts.iter().filter(|a| !a.rest) {
            writeln!(out, "        {},", rust_ident(&acc.name)).unwrap();
        }
        writeln!(out, "    ];").unwrap();
        for acc in ix.accounts.iter().filter(|a| a.rest) {
            writeln!(out, "    account_ids.extend({});", rust_ident(&acc.name)).unwrap();
        }

        // Build instruction data
        writeln!(out).unwrap();
        writeln!(out, "    // Build result with account_ids and serialized instruction args").unwrap();
        writeln!(out, "    let result = json!({{").unwrap();
        writeln!(out, "        \"success\": true,").unwrap();
        writeln!(out, "        \"account_ids\": account_ids.iter().map(|a| a.to_string()).collect::<Vec<_>>(),").unwrap();
        // Include parsed args for the caller to use
        writeln!(out, "        \"instruction_name\": \"{}\",", ix.name).unwrap();
        writeln!(out, "    }});").unwrap();
        writeln!(out, "    Ok(result.to_string())").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }

    // Free string
    writeln!(out, "/// Free a string returned by any {prefix}_* function.").unwrap();
    writeln!(out, "#[no_mangle]").unwrap();
    writeln!(out, "pub extern \"C\" fn {prefix}_free_string(s: *mut c_char) {{").unwrap();
    writeln!(out, "    if !s.is_null() {{ unsafe {{ drop(CString::from_raw(s)) }}; }}").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Version
    writeln!(out, "#[no_mangle]").unwrap();
    writeln!(out, "pub extern \"C\" fn {prefix}_version() -> *mut c_char {{").unwrap();
    writeln!(out, "    to_cstring(\"{}\".to_string())", idl.version).unwrap();
    writeln!(out, "}}").unwrap();

    Ok(out)
}

/// Generate a C header file from an IDL.
pub fn generate_header(idl: &LezIdl) -> Result<String, String> {
    let mut out = String::new();
    let prefix = snake_case(&idl.name);
    let guard = format!("{}_FFI_H", prefix.to_uppercase());

    writeln!(out, "/* Auto-generated C header for {} FFI. DO NOT EDIT. */", idl.name).unwrap();
    writeln!(out, "#ifndef {guard}").unwrap();
    writeln!(out, "#define {guard}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#ifdef __cplusplus").unwrap();
    writeln!(out, "extern \"C\" {{").unwrap();
    writeln!(out, "#endif").unwrap();
    writeln!(out).unwrap();

    for ix in &idl.instructions {
        let fn_name = format!("{}_{}", prefix, snake_case(&ix.name));
        writeln!(out, "/* {} instruction */", ix.name).unwrap();
        writeln!(out, "char* {fn_name}(const char* args_json);").unwrap();
        writeln!(out).unwrap();
    }

    writeln!(out, "void {prefix}_free_string(char* s);").unwrap();
    writeln!(out, "char* {prefix}_version(void);").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#ifdef __cplusplus").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out, "#endif").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#endif /* {guard} */").unwrap();

    Ok(out)
}
